const topics = {
  'digital-logic-design-topic-1-introduction': ['Digital systems and abstraction', 'Digital logic represents information with discrete voltage ranges interpreted as binary 0 and 1.', 'A combinational output depends on current inputs; a sequential output also depends on stored state.', 'A thermostat controller can encode cold=0 and warm=1, then use logic to switch a heater.', 'Classify a memoryless two-input alarm as combinational or sequential.', 'Combinational, because its output depends only on the present sensor inputs.'],
  'digital-logic-design-topic-2-number-systems-binary-octal-hexadecimal': ['Positional number systems', 'Binary, octal, and hexadecimal use bases 2, 8, and 16 to encode numeric values.', 'The value of digits d_n...d_0 in base b is the sum of d_i b^i; one octal digit maps to 3 bits and one hexadecimal digit to 4 bits.', '101101₂ = 32+8+4+1 = 45₁₀ = 55₈ = 2D₁₆.', 'Convert 111010₂ to hexadecimal.', '3A₁₆, because 111010 is padded and grouped as 0011 1010.'],
  'digital-logic-design-topic-3-number-ranges': ['Ranges fixed by bit width', 'An n-bit word has 2^n distinct patterns; interpretation determines its numeric range.', 'Unsigned range is 0 to 2^n-1; n-bit two’s-complement range is -2^(n-1) to 2^(n-1)-1.', 'Eight bits represent 0...255 unsigned or -128...127 in two’s complement.', 'State the signed two’s-complement range for 6 bits.', '-32 to 31.'],
  'digital-logic-design-topic-4-arithmetic-operations': ['Binary arithmetic', 'Binary addition, subtraction, multiplication, and division follow positional arithmetic with base-2 carries or borrows.', 'For one column, 1+1=10₂ and 1+1+1=11₂.', '1011₂ + 0110₂ = 10001₂.', 'Add 1101₂ and 0011₂.', '10000₂.'],
  'digital-logic-design-topic-5-conversion-from-decimal-to-other-bases': ['Converting decimal values', 'Repeated division converts an integer to another base; repeated multiplication converts a fractional part.', 'Read integer remainders from last to first; read fractional integer parts in generated order.', '25 divided repeatedly by 2 gives remainders that read as 11001₂.', 'Convert 42₁₀ to binary.', '101010₂, since 42=32+8+2.'],
  'digital-logic-design-topic-6-negative-number-representations': ['Encoding negative integers', 'Signed magnitude, one’s complement, and two’s complement encode a sign differently.', 'Form an n-bit two’s-complement negative by complementing the positive pattern and adding 1.', 'With 8 bits, +5=00000101 and -5=11111011.', 'Write -18 in 8-bit two’s complement.', '11101110.'],
  'digital-logic-design-topic-7-binary-logic-and-gates': ['Gates implement Boolean functions', 'NOT inverts; AND requires every input high; OR requires at least one input high.', 'Gate behavior is defined for every input combination by its truth table.', 'For A=1 and B=0: AND=0, OR=1, and NOT A=0.', 'Find Y=(A AND B) OR C for A=1, B=0, C=1.', '1.'],
  'digital-logic-design-topic-8-boolean-algebra': ['Algebra for binary variables', 'Boolean algebra manipulates variables limited to 0 and 1 using complement, product, and sum.', 'Identity, complement, absorption, distributive, and De Morgan laws preserve the represented function.', 'A+AB=A by absorption; (AB)’=A’+B’ by De Morgan’s law.', 'Simplify X+X’Y.', 'X+Y.'],
  'digital-logic-design-topic-9-standard-forms': ['Canonical minterms and maxterms', 'Canonical SOP is a sum of minterms; canonical POS is a product of maxterms, each containing every variable.', 'F=Σm(indices where F=1)=ΠM(indices where F=0).', 'For F(A,B)=1 at 1 and 2, F=Σm(1,2)=A’B+AB’.', 'Write the canonical SOP for a 2-variable function high at 0 and 3.', 'A’B’+AB, or Σm(0,3).'],
  'digital-logic-design-topic-10-sop-and-pos': ['Two-level SOP and POS', 'SOP ORs product terms; POS ANDs sum terms, and either form may be canonical or simplified.', 'Group truth-table 1s for SOP and 0s for POS.', 'F=A’B+AC is SOP; (A+B)(A’+C) is POS.', 'Identify the form of (X+Y’)(Y+Z).', 'Product of sums (POS).'],
  'digital-logic-design-topic-11-expressing-functions-from-one-form-into-another': ['Equivalent function forms', 'Truth tables, canonical notation, Boolean expressions, and circuits can describe the same function.', 'To convert Σm to ΠM, list every missing index from the full index range.', 'For three variables, Σm(1,3,7)=ΠM(0,2,4,5,6).', 'Convert F=Σm(0,2,3) for two variables to canonical POS.', 'F=ΠM(1).'],
  'digital-logic-design-topic-12-k-maps-sop-pos': ['Karnaugh-map minimization', 'A K-map places truth-table cells in Gray-code order so adjacent cells differ in one variable.', 'For SOP group adjacent 1s; for POS group adjacent 0s, using power-of-two rectangles as large as possible.', 'Four adjacent 1s in a 3-variable map eliminate two variables and produce one literal.', 'What sizes may valid K-map groups have?', '1, 2, 4, 8, and other powers of two.'],
  'digital-logic-design-topic-13-manipulating-maps': ['Using K-map adjacency', 'K-map edges wrap, groups may overlap, and every required cell must be covered.', 'Choose essential prime implicants first, then cover remaining cells with the fewest literals.', 'The leftmost and rightmost columns are adjacent because their Gray codes differ in one bit.', 'May a corner cell group with the other three corners?', 'Yes; the four corners form a wrapped 2-by-2 group.'],
  'digital-logic-design-topic-14-dont-care-conditions': ['Unspecified input combinations', 'A don’t-care marks an input combination whose output is irrelevant or cannot occur.', 'Treat each X as 0 or 1 independently, whichever produces simpler logic; it need not be grouped.', 'In a BCD circuit, binary inputs 1010 through 1111 can be don’t-cares.', 'Must every don’t-care cell be included in a K-map group?', 'No; use it only when it improves simplification.'],
  'digital-logic-design-topic-15-k-map-dont-care-conditions': ['Optimizing K-maps with X cells', 'Don’t-care cells can enlarge K-map groups without imposing required output values.', 'A group may contain required cells plus X cells, but never a cell fixed to the opposite value.', 'A pair of 1s beside two Xs can become a group of four and eliminate another literal.', 'Can an SOP group contain a fixed 0 to become larger?', 'No; it may contain 1s and useful don’t-cares only.'],
  'digital-logic-design-topic-16-nand-nor-and-exclusive-or-gates-and-circuits': ['Universal and parity gates', 'NAND and NOR are universal; XOR detects unequal inputs and XNOR detects equal inputs.', 'A NAND used with tied inputs inverts: NAND(A,A)=A’.', 'A half-adder uses XOR for sum and AND for carry.', 'Implement NOT X using only NOR.', 'Connect X to both NOR inputs: NOR(X,X)=X’.'],
  'digital-logic-design-topic-17-integrated-circuits': ['Logic in packaged devices', 'An integrated circuit combines gates or larger functions on one semiconductor die.', 'Key parameters include fan-in, fan-out, propagation delay, power dissipation, and noise margin.', 'If one output is rated for fan-out 10, it should drive no more than ten standard inputs of that family.', 'What parameter measures input-to-output response time?', 'Propagation delay.'],
  'digital-logic-design-topic-18-positive-and-negative-logic': ['Assigning levels to logic values', 'Positive logic maps the higher voltage to 1; negative logic maps it to 0.', 'Changing the logic convention changes the Boolean interpretation without changing the physical voltage waveform.', 'A physical high level is logic 1 under positive logic but logic 0 under negative logic.', 'Under negative logic, what value does the low voltage represent?', 'Logic 1.'],
  'digital-logic-design-topic-19-combinational-circuits': ['Memoryless logic networks', 'A combinational circuit maps present input combinations directly to outputs without stored state.', 'Its specification is a Boolean function or truth table; feedback storage is absent.', 'A 2-to-1 multiplexer selects D0 or D1 from the current select input.', 'Is a full adder combinational?', 'Yes; sum and carry depend only on current inputs.'],
  'digital-logic-design-topic-20-analysis-procedure': ['Deriving behavior from a circuit', 'Combinational analysis determines expressions and a truth table from a given gate network.', 'Label intermediate nodes, write gate expressions in signal order, then evaluate or simplify outputs.', 'If N=A+B and Y=NB’, then Y=(A+B)B’=AB’.', 'Analyze Y=(A XOR B)C for A=1, B=1, C=1.', '0, because A XOR B is 0.'],
  'digital-logic-design-topic-21-design-procedure': ['From specification to circuit', 'Combinational design translates a word problem into inputs, outputs, a truth table, minimized equations, and gates.', 'Define active levels before constructing the truth table, then verify every specified case.', 'A majority circuit sets Y=1 for minterms 3,5,6,7, yielding AB+AC+BC.', 'What should be defined before filling a design truth table?', 'The meaning and active level of every input and output.'],
  'digital-logic-design-topic-22-decoders': ['Activating one output', 'An n-to-2^n decoder asserts the output corresponding to the binary input code.', 'With active-high outputs, output Y_i is minterm i; an enable input controls operation.', 'A 2-to-4 decoder receiving 10 activates Y2.', 'Which output activates for input 011 on a 3-to-8 decoder?', 'Y3.'],
  'digital-logic-design-topic-23-encoders': ['Encoding an active line', 'A 2^n-to-n encoder outputs the binary index of one asserted input.', 'A basic encoder assumes exactly one input is active; multiple active inputs make the result ambiguous.', 'If D5 alone is high on an 8-to-3 encoder, the output is 101.', 'What is the output when D6 alone is active on an 8-to-3 encoder?', '110.'],
  'digital-logic-design-topic-24-priority-encoders': ['Resolving simultaneous requests', 'A priority encoder reports the highest-priority asserted input and often a valid bit.', 'Lower-priority inputs are ignored whenever a higher-priority input is active.', 'With D3 highest priority, D3=1 and D1=1 produces code 11.', 'For a 4-to-2 priority encoder with D3 highest, what code results from D2=1 and D0=1?', '10, the code for D2.'],
  'digital-logic-design-topic-25-multiplexers': ['Selecting one data source', 'A multiplexer routes one of several data inputs to one output using select lines.', 'A 2^n-to-1 MUX needs n select bits; Y=D0S’+D1S for a 2-to-1 MUX.', 'For D0=0, D1=1, and S=1, Y=1.', 'How many select lines does an 8-to-1 MUX need?', '3.'],
  'digital-logic-design-topic-26-demultiplexers': ['Routing one input to a destination', 'A demultiplexer sends one data input to one selected output.', 'A 1-to-2 DEMUX has Y0=DS’ and Y1=DS.', 'For D=1 and S=0, Y0=1 and Y1=0.', 'For a 1-to-4 DEMUX with D=1 and select 10, which output is high?', 'Y2.'],
  'digital-logic-design-topic-27-binary-adders': ['Adding multi-bit words', 'Binary adders combine one-bit adder stages to produce sum bits and carries.', 'At bit i, inputs include operands A_i and B_i plus carry C_i; the stage produces S_i and C_(i+1).', 'Adding 0101 and 0011 yields 1000.', 'Add 0110₂ and 0101₂.', '1011₂.'],
  'digital-logic-design-topic-28-half-adder': ['Adding two single bits', 'A half adder adds A and B but has no carry input.', 'Sum S=A XOR B; carry C=AB.', 'For A=1 and B=1, S=0 and C=1.', 'Find S and C for A=1, B=0.', 'S=1, C=0.'],
  'digital-logic-design-topic-29-full-adder': ['Adding three single bits', 'A full adder adds A, B, and carry-in C_in.', 'S=A XOR B XOR C_in; C_out=AB+AC_in+BC_in.', 'For 1+0+1, S=0 and C_out=1.', 'Find the outputs for A=1, B=1, C_in=1.', 'S=1, C_out=1.'],
  'digital-logic-design-topic-30-ripple-carry': ['Carry propagation through stages', 'A ripple-carry adder connects each stage carry-out to the next stage carry-in.', 'Worst-case delay grows roughly with word length because a carry may traverse every stage.', 'In 1111+0001, the carry ripples through all four bit positions.', 'Why is a 32-bit ripple-carry adder slower than a 4-bit one?', 'Its critical carry path passes through more full-adder stages.'],
  'digital-logic-design-topic-31-carry-lookahead': ['Computing carries in parallel', 'Carry-lookahead logic uses generate and propagate signals to avoid waiting for carries to ripple.', 'G_i=A_iB_i, P_i=A_i XOR B_i, and C_(i+1)=G_i+P_iC_i.', 'If G0=1, then C1=1 regardless of C0.', 'Given G0=0, P0=1, C0=1, find C1.', '1.'],
  'digital-logic-design-topic-32-binary-subtraction': ['Subtracting binary words', 'Binary subtraction may use borrows directly or add the two’s complement of the subtrahend.', 'A-B=A+(two’s complement of B), discarding the final carry in fixed width.', 'With 4 bits, 0111-0011 = 0111+1101 = 0100.', 'Compute 1001₂-0010₂.', '0111₂.'],
  'digital-logic-design-topic-33-signed-binary-numbers': ['Operating on signed values', 'Two’s-complement arithmetic uses one representation for zero and the same adder for signed addition and subtraction.', 'To widen a two’s-complement number, replicate its sign bit; interpret the MSB with weight -2^(n-1).', '11110110₂ as 8-bit two’s complement equals -10.', 'Interpret 1101₂ as a 4-bit two’s-complement number.', '-3.'],
  'digital-logic-design-topic-34-overflow': ['Detecting out-of-range results', 'Signed overflow occurs when a mathematically correct result cannot fit the available two’s-complement range.', 'Overflow occurs when equal-sign operands produce a result with the opposite sign; equivalently, carry into MSB differs from carry out.', 'Four-bit 0111+0010 gives 1001, signaling overflow because 9 exceeds +7.', 'Does 4-bit 1011+1101 overflow?', 'No; -5 + -3 equals -8, which is representable as 1000.'],
  'digital-logic-design-topic-35-sequential-circuits': ['Logic with stored state', 'A sequential circuit combines combinational logic with memory, so outputs may depend on present inputs and previous state.', 'Synchronous circuits update state at clock events; next state is a function of current state and inputs.', 'A counter advances from its stored count on each active clock edge.', 'Why can two identical input values yield different sequential-circuit outputs?', 'The circuits may begin in different stored states.'],
  'digital-logic-design-topic-36-latches': ['Level-sensitive storage', 'A latch stores one bit and may respond throughout an active enable level.', 'For an active-high D latch, Q follows D while enable=1 and holds while enable=0.', 'If D changes from 0 to 1 while enable is high, Q becomes 1.', 'What happens to Q when a D latch enable is low?', 'It retains its previous value.'],
  'digital-logic-design-topic-37-flip-flops': ['Edge-triggered storage', 'A flip-flop samples inputs on a specified clock edge and holds the resulting state between edges.', 'D: Q+=D; T: Q+=T XOR Q; JK: 00 hold, 01 reset, 10 set, 11 toggle.', 'A T flip-flop with T=1 toggles on every active edge.', 'A JK flip-flop has J=K=1 and Q=0. What is Q after one active edge?', '1.'],
  'digital-logic-design-topic-38-sequential-circuit-analysis': ['Finding next-state behavior', 'Sequential analysis derives flip-flop input equations, next-state equations, outputs, and a state table or diagram.', 'Substitute excitation equations into the flip-flop characteristic equation, then evaluate every state/input combination.', 'For a D flip-flop with D=X XOR Q, X=1 makes the state toggle.', 'For D=XQ’ and current Q=0, X=1, find Q+.', '1.'],
  'digital-logic-design-topic-39-state-diagram': ['Visualizing finite-state behavior', 'A state diagram uses nodes for states and directed arcs for transitions.', 'Moore outputs label states; Mealy outputs label transitions and may respond immediately to inputs.', 'A two-state parity machine moves between Even and Odd whenever input 1 arrives.', 'Where are outputs written in a Mealy diagram?', 'On transitions, usually with input/output labels.'],
  'digital-logic-design-topic-40-sequential-circuit-design-word-problems': ['Turning behavior into an FSM', 'Sequential design converts a timed behavior description into states, transitions, encodings, flip-flop equations, and output logic.', 'Choose states that retain only the history needed to determine future behavior, then verify reset and every transition.', 'A 101 detector needs states representing no match, seen 1, and seen 10.', 'What history must a sequence-detector state preserve?', 'Only the relevant input suffix needed to recognize a future sequence.'],
  'digital-logic-design-topic-41-registers-and-counters': ['Multi-bit storage and sequences', 'A register stores a word; a counter is a register whose next-state logic follows a prescribed count sequence.', 'An n-bit binary counter has up to 2^n states; registers use one flip-flop per stored bit.', 'A 4-bit register stores four bits, while a 4-bit binary counter cycles through 16 states.', 'How many flip-flops are required for an 8-bit register?', '8.'],
  'digital-logic-design-topic-42-register-with-parallel-load': ['Loading a word at once', 'A parallel-load register selects either new external data or its current value for every bit.', 'For each D input, D_i=Load·I_i+Load’·Q_i.', 'When Load=1, four input bits are captured together on the next active edge.', 'What happens at the next edge when Load=0?', 'The register reloads its current value and therefore holds.'],
  'digital-logic-design-topic-43-shift-registers': ['Moving stored bits', 'A shift register moves each stored bit one position per active clock and accepts a serial input.', 'SISO, SIPO, PISO, and PIPO describe serial/parallel input and output arrangements.', 'Right-shifting 1011 with serial-in 0 produces 0101 when the leftmost bit receives the input.', 'Name a register that accepts serial data and exposes all bits together.', 'Serial-in, parallel-out (SIPO).'],
  'digital-logic-design-topic-44-shift-register-with-parallel-load': ['Loading or shifting selectively', 'A shift register with parallel load can capture an entire word or shift it under mode control.', 'A multiplexer before each flip-flop selects parallel data, neighboring shift data, or hold feedback.', 'Load 1010 in one edge, then right-shift with serial-in 1 to obtain 1101.', 'Why are multiplexers used before the flip-flop inputs?', 'They select which next-state source each bit receives.'],
  'digital-logic-design-topic-45-serial-and-parallel-counters': ['Asynchronous and synchronous counting', 'A serial/ripple counter clocks later stages from earlier outputs; a parallel/synchronous counter clocks all stages together.', 'Ripple counters accumulate stage delays; synchronous counters compute toggles in parallel.', 'In a synchronous 3-bit up counter, Q2 toggles when Q1Q0=1 before the edge.', 'Which counter style is preferred for higher clock speed?', 'A parallel or synchronous counter.'],
  'digital-logic-design-topic-46-up-down-binary-counter': ['Counting in either direction', 'An up-down counter increments or decrements according to a direction control.', 'For modulo 2^n arithmetic, up adds 1 and down subtracts 1, wrapping at the endpoints.', 'A 3-bit down counter moves from 000 to 111.', 'What follows 101 in a 3-bit up counter?', '110.'],
  'digital-logic-design-topic-47-binary-counter-with-parallel-load': ['Presettable counting', 'A counter with parallel load can start from an external value as well as count normally.', 'Control priority must be defined, commonly reset first, then load, then count, then hold.', 'Loading 1001 followed by one enabled up-count produces 1010.', 'If load has priority over count and both are asserted, what happens?', 'The external value is loaded.'],
  'digital-logic-design-topic-48-programmable-logic-technologies': ['Configurable digital hardware', 'Programmable logic implements user-defined Boolean functions by configuring connections or logic resources.', 'ROM, PLA, PAL, CPLD, and FPGA devices trade flexibility, capacity, speed, and configuration method.', 'A PLA programs both its AND and OR arrays for custom two-level logic.', 'Which technology is appropriate for a large reconfigurable datapath?', 'An FPGA.'],
  'digital-logic-design-topic-49-read-only-memory': ['Truth tables stored as words', 'ROM stores fixed or programmed words addressed by input bits and can implement combinational functions.', 'An n-address-bit, m-output ROM contains 2^n words of m bits.', 'A 3-by-2 input/output specification fits an 8-word by 2-bit ROM.', 'What ROM organization implements four inputs and three outputs?', '16 words by 3 bits.'],
  'digital-logic-design-topic-50-programmable-logic-arrays': ['Programmable AND and OR planes', 'A PLA implements multiple SOP functions with programmable product terms and programmable output sums.', 'Shared product terms can reduce hardware when several outputs use the same conjunction.', 'Outputs F1=AB+C and F2=AB+D can share the product term AB.', 'What two arrays are programmable in a PLA?', 'Both the AND array and the OR array.'],
  'digital-logic-design-topic-51-programmable-array-logic-devices': ['Programmable AND, fixed OR', 'A PAL typically uses a programmable AND array feeding a fixed OR structure.', 'PALs are less flexible than PLAs but often simpler and faster for supported product-term limits.', 'Each output can combine only the number of product terms wired to its fixed OR gate.', 'How does a PAL differ from a PLA?', 'A PAL normally has a programmable AND plane but a fixed OR plane.'],
  'digital-logic-design-topic-52-introduction-to-fpgas': ['Reconfigurable logic fabrics', 'An FPGA contains configurable logic blocks, routing, I/O resources, and often memories or arithmetic blocks.', 'A hardware description is synthesized, placed, routed, and loaded as a configuration bitstream.', 'A lookup table can implement a small Boolean function while flip-flops store pipeline state.', 'What stage connects placed logic blocks through FPGA interconnect?', 'Routing.'],
}

function makeSeed(title, [heading, explanation, rule, example, prompt, answer]) {
  return {
    note: {
      heading,
      explanation,
      keyPoints: [
        `Definition: ${explanation}`,
        `Formula/rule: ${rule}`,
        `Exam focus: derive or apply the defining rule for ${title.toLowerCase()} and show intermediate logic values.`,
        `Common mistake: memorizing a label for ${title.toLowerCase()} without checking bit width, active level, or stated operating conditions.`,
      ],
      example,
    },
    practice: {
      prompt,
      hint: `Use this rule from the notes: ${rule}`,
      answer,
      explanation: `The worked result is ${answer} It follows from the stated rule and the given input conditions.`,
    },
    quiz: {
      prompt: `Which statement correctly describes ${title.toLowerCase()}?`,
      choices: [explanation, 'Its result is independent of all inputs and stored state.', 'It always uses decimal arithmetic internally.', 'It is valid only when every signal is logic 1.'],
      correctIndex: 0,
      explanation: `${explanation} The other choices contradict the topic’s defining behavior.`,
    },
  }
}

export const digitalLogicDesignTopics = Object.fromEntries(
  Object.entries(topics).map(([id, content]) => {
    const title = id.replace('digital-logic-design-topic-', '').replace(/^\d+-/, '').replaceAll('-', ' ')
    return [id, makeSeed(title, content)]
  }),
)
