const topic = ({ title, definition, rule, explanation, example, practice, answer, hint, quiz, choices, correctIndex, quizExplanation, examFocus, mistake }) => ({
  note: {
    heading: title,
    explanation,
    keyPoints: [
      `Definition: ${definition}`,
      `Formula/rule: ${rule}`,
      `Exam focus: ${examFocus}`,
      `Common mistake: ${mistake}`,
    ],
    example,
  },
  practice: { prompt: practice, hint, answer, explanation: `The result follows because ${answer.toLowerCase()}` },
  quiz: { prompt: quiz, choices, correctIndex, explanation: quizExplanation },
})

export const probabilityAndStatisticsTopics = {
  'probability-and-statistics-topic-1-introduction-to-statistics-and-data-analysis': topic({
    title: 'Statistics turns data into evidence', definition: 'Descriptive statistics summarize observed data; inferential statistics use a sample to reason about a population.', rule: 'Always identify the observational units, variables, and whether each variable is categorical or quantitative.', explanation: 'Statistical analysis begins by asking what was measured, on whom, and for what purpose. Graphs and numerical summaries reveal patterns, while inference quantifies how far conclusions may extend.', example: 'For 40 response times, a histogram and median describe the sample; a confidence interval can estimate the population median or mean.', practice: 'Classify student major and weekly study hours.', hint: 'Ask whether arithmetic on the recorded values is meaningful.', answer: 'Major is categorical; weekly study hours is quantitative.', quiz: 'Which task is inferential?', choices: ['Drawing a sample histogram', 'Computing its median', 'Estimating a population mean from the sample', 'Sorting observations'], correctIndex: 2, quizExplanation: 'Inference generalizes from observed sample data to an unobserved population quantity.', examFocus: 'distinguish descriptive analysis from inference and classify variables', mistake: 'calculating before defining the population and variables',
  }),
  'probability-and-statistics-topic-2-statistical-inference': topic({
    title: 'Inference quantifies uncertainty', definition: 'Statistical inference estimates population parameters or tests claims using sample statistics.', rule: 'An estimate should be reported with uncertainty, such as a standard error, confidence interval, or test result.', explanation: 'Samples vary, so a statistic is not normally equal to its parameter. Inference uses a probability model for sampling variation to judge plausible parameter values.', example: 'A sample mean of 72 with standard error 2 gives an approximate 95% interval of 72 +/- 4.', practice: 'A sample estimate is 50 with standard error 3. Give the approximate 95% interval using two standard errors.', hint: 'Subtract and add 2(3).', answer: 'The approximate interval is 44 to 56.', quiz: 'What creates sampling uncertainty?', choices: ['Using different random samples', 'Writing units', 'Sorting a table', 'Naming a variable'], correctIndex: 0, quizExplanation: 'Different random samples generally produce different statistics.', examFocus: 'connect parameters, statistics, sampling variability, estimation, and testing', mistake: 'presenting a point estimate as if it were exact',
  }),
  'probability-and-statistics-topic-3-samples': topic({
    title: 'A sample is the observed subset', definition: 'A sample is the collection of population units actually selected and measured.', rule: 'A useful sample needs a defined sampling frame and a selection process that limits bias.', explanation: 'Sample size affects precision, but selection quality determines whether the sample represents the target population. A large biased sample can still mislead.', example: 'The 200 voters randomly selected from the register are the sample; all eligible voters are the target population.', practice: 'A factory inspects every 50th item and measures 80 items. Identify the sample.', hint: 'Name the units actually measured.', answer: 'The sample is the 80 inspected items.', quiz: 'Which change most directly improves representativeness?', choices: ['Use random selection from the target frame', 'Round every value', 'Use a larger font', 'Remove unusual observations'], correctIndex: 0, quizExplanation: 'Random selection helps avoid systematic over- or under-representation.', examFocus: 'identify sample, frame, sampling unit, and possible selection bias', mistake: 'assuming a large convenience sample is representative',
  }),
  'probability-and-statistics-topic-4-populations': topic({
    title: 'Define the population precisely', definition: 'A population is the complete set of units about which a study seeks conclusions.', rule: 'State inclusion criteria, location, and time period so the target population is unambiguous.', explanation: 'The population determines what a parameter describes and where an inference may apply. The accessible population may be narrower than the intended target.', example: 'For a 2026 campus survey, all students enrolled that term form the target population, not students from every year.', practice: 'Define a population for estimating battery life of a new phone model sold this month.', hint: 'Specify the units and relevant production or sales period.', answer: 'All units of that phone model sold this month form the population.', quiz: 'Which quantity describes a population?', choices: ['Parameter', 'Statistic', 'Sample size only', 'Response rate only'], correctIndex: 0, quizExplanation: 'A parameter is a numerical characteristic of the population.', examFocus: 'distinguish target, accessible, and sampled populations', mistake: 'generalizing beyond the population represented by the sampling frame',
  }),
  'probability-and-statistics-topic-5-role-of-probability': topic({
    title: 'Probability models uncertainty', definition: 'Probability assigns numerical measures from 0 to 1 to uncertain events.', rule: 'For a sample space S, P(S)=1, P(A)>=0, and probabilities of disjoint events add.', explanation: 'Probability provides the mathematical link between random data generation and statistical conclusions. It predicts long-run behavior and measures sampling uncertainty.', example: 'If a fair die is rolled, probability models which face appears even though a single result is unpredictable.', practice: 'A fair coin is tossed twice. Find the probability of exactly one head.', hint: 'List HH, HT, TH, TT.', answer: 'The probability is 2/4 = 1/2.', quiz: 'Why is probability central to inference?', choices: ['It models sampling variation', 'It removes all uncertainty', 'It guarantees unbiased data', 'It replaces study design'], correctIndex: 0, quizExplanation: 'Sampling distributions use probability to quantify how statistics vary.', examFocus: 'explain how probability supports estimation and hypothesis testing', mistake: 'interpreting probability as certainty about one trial',
  }),
  'probability-and-statistics-topic-6-sampling-procedures': topic({
    title: 'Sampling design controls selection bias', definition: 'A sampling procedure is a rule for selecting units, such as simple random, stratified, cluster, or systematic sampling.', rule: 'In a simple random sample of size n, every size-n subset has the same chance of selection.', explanation: 'Different designs trade cost, precision, and coverage. Stratification samples within important groups; cluster sampling selects natural groups; systematic sampling uses a random start and fixed step.', example: 'Sampling students separately within each program is stratified sampling and guarantees program representation.', practice: 'Name the design: randomly choose 5 classes, then survey every student in them.', hint: 'Whole natural groups are selected.', answer: 'This is cluster sampling.', quiz: 'Which design samples from every defined subgroup?', choices: ['Stratified', 'Cluster', 'Convenience', 'Voluntary response'], correctIndex: 0, quizExplanation: 'Stratified sampling independently samples units within each stratum.', examFocus: 'identify designs and compare bias and precision', mistake: 'confusing selecting whole clusters with sampling inside every stratum',
  }),
  'probability-and-statistics-topic-7-discrete-and-continuous-data': topic({
    title: 'Data type determines valid models', definition: 'Discrete data take countable values; continuous data can take any value in an interval.', rule: 'Use probability mass P(X=x) for discrete variables and density areas P(a<X<b) for continuous variables.', explanation: 'Counts are usually discrete, while measurements such as time and mass are continuous. A continuous variable has probability zero at any exact point even though intervals have positive probability.', example: 'Number of failed servers is discrete; repair time is continuous.', practice: 'Classify the number of calls and the duration of a call.', hint: 'Counts are countable; measurements vary along a continuum.', answer: 'Number of calls is discrete; duration is continuous.', quiz: 'For a continuous random variable, what is P(X=x)?', choices: ['0', '1', 'Always 1/2', 'Undefined'], correctIndex: 0, quizExplanation: 'Probability is density area, and a single point has zero width.', examFocus: 'classify variables and select mass or density interpretations', mistake: 'treating a density value as a point probability',
  }),
  'probability-and-statistics-topic-8-statistical-modeling': topic({
    title: 'Models simplify data-generating processes', definition: 'A statistical model is a set of probability distributions proposed for observed data.', rule: 'Separate systematic structure from random error and check assumptions against residuals or observed patterns.', explanation: 'Models approximate reality to explain relationships and predict outcomes. Useful modeling includes assumptions, parameter estimation, diagnostics, and honest limits.', example: 'Y=beta0+beta1x+error models a linear mean response with unexplained random variation.', practice: 'In Y=10+2x+error, predict Y at x=3 when the error is taken as zero.', hint: 'Substitute x=3 into the systematic part.', answer: 'The fitted value is 16.', quiz: 'What should be examined after fitting a model?', choices: ['Assumptions and residuals', 'Only the title', 'Only sample order', 'No further evidence'], correctIndex: 0, quizExplanation: 'Diagnostics test whether model assumptions are plausible.', examFocus: 'state model components, assumptions, fit, and diagnostic checks', mistake: 'treating an approximate model as literal truth',
  }),
  'probability-and-statistics-topic-9-types-of-statistical-studies': topic({
    title: 'Study design limits causal claims', definition: 'An observational study records existing exposures; an experiment assigns treatments to units.', rule: 'Random assignment supports causal comparison; random sampling supports generalization to a population.', explanation: 'Experiments can balance lurking variables through random assignment. Observational associations may be explained by confounding, even with a large sample.', example: 'Assigning volunteers randomly to two interfaces is an experiment; comparing people who chose each interface is observational.', practice: 'Researchers record exercise habits and blood pressure without assigning exercise. Classify the study.', hint: 'Ask whether the explanatory condition was imposed.', answer: 'It is an observational study.', quiz: 'Which feature most supports cause-and-effect?', choices: ['Random assignment', 'Random sampling alone', 'A large correlation', 'A census table'], correctIndex: 0, quizExplanation: 'Random assignment tends to balance confounders between treatment groups.', examFocus: 'distinguish survey, observational study, and randomized experiment', mistake: 'claiming causation from association alone',
  }),
  'probability-and-statistics-topic-10-probability': topic({
    title: 'Probability obeys consistent axioms', definition: 'Probability is a function assigning each event a number between 0 and 1.', rule: 'P(A complement)=1-P(A), and if A and B are disjoint then P(A union B)=P(A)+P(B).', explanation: 'A probability model combines a sample space with event probabilities. Axioms ensure that complements, unions, and conditional statements remain coherent.', example: 'If P(defect)=0.03, then P(no defect)=0.97.', practice: 'If P(rain)=0.35, find P(no rain).', hint: 'Use the complement rule.', answer: 'P(no rain)=1-0.35=0.65.', quiz: 'Which value cannot be a probability?', choices: ['-0.2', '0', '0.45', '1'], correctIndex: 0, quizExplanation: 'Probabilities must lie from 0 through 1.', examFocus: 'apply axioms, complements, unions, and probability interpretations', mistake: 'adding probabilities of overlapping events without subtracting overlap',
  }),
  'probability-and-statistics-topic-11-sample-space': topic({
    title: 'The sample space lists possible outcomes', definition: 'A sample space S is the set of all outcomes of a random experiment.', rule: 'Events are subsets of S and the chosen sample space must be mutually exclusive and exhaustive.', explanation: 'A clear sample space prevents omitted or double-counted outcomes. It may be finite, countably infinite, or continuous depending on the experiment.', example: 'For two coin tosses, S={HH, HT, TH, TT}.', practice: 'Write the sample space for rolling one die and recording parity.', hint: 'The recorded outcomes are categories, not face numbers.', answer: 'S={even, odd}.', quiz: 'What must a sample space include?', choices: ['Every possible outcome', 'Only likely outcomes', 'Only favorable outcomes', 'Exactly two outcomes'], correctIndex: 0, quizExplanation: 'The sample space is exhaustive by definition.', examFocus: 'construct an appropriate sample space and express events as subsets', mistake: 'mixing outcomes defined at different levels of detail',
  }),
  'probability-and-statistics-topic-12-events': topic({
    title: 'Events combine outcomes', definition: 'An event is a subset of the sample space; it occurs when the observed outcome belongs to that subset.', rule: 'Union means A or B, intersection means A and B, and complement means not A.', explanation: 'Set operations translate verbal probability statements into precise events. Mutually exclusive events have empty intersection.', example: 'On a die, A={2,4,6} and B={4,5,6}; A intersection B={4,6}.', practice: 'For S={1,2,3,4,5,6}, let A={2,4,6}. Find A complement.', hint: 'Keep all outcomes in S not in A.', answer: 'A complement is {1,3,5}.', quiz: 'When are events mutually exclusive?', choices: ['Their intersection is empty', 'Their union is empty', 'They have equal probability', 'They are independent'], correctIndex: 0, quizExplanation: 'Mutually exclusive events cannot occur together.', examFocus: 'translate words into union, intersection, and complement notation', mistake: 'assuming mutually exclusive events are independent',
  }),
  'probability-and-statistics-topic-13-counting-sample-points': topic({
    title: 'Count outcomes without listing them all', definition: 'Counting principles find the number of sample points produced by sequential choices or selections.', rule: 'Multiplication rule: m choices followed by n choices give mn outcomes; permutations order objects, combinations do not.', explanation: 'Counting converts equally likely outcome problems into probability ratios. The key decision is whether order matters and whether repetition is allowed.', example: 'Choosing president then secretary from 5 people gives 5P2=5x4=20 assignments.', practice: 'How many 2-person committees can be chosen from 5 people?', hint: 'Order does not matter, so use a combination.', answer: 'There are C(5,2)=10 committees.', quiz: 'Which expression counts ordered selections of r from n?', choices: ['n!/(n-r)!', 'n!/[r!(n-r)!]', 'n+r', 'n/r'], correctIndex: 0, quizExplanation: 'The permutation formula retains order.', examFocus: 'choose multiplication, permutation, or combination methods correctly', mistake: 'using permutations when order does not matter',
  }),
  'probability-and-statistics-topic-14-probability-of-an-event': topic({
    title: 'Event probability sums outcome probability', definition: 'The probability of an event is the total probability assigned to its outcomes.', rule: 'For equally likely finite outcomes, P(A)=number of outcomes in A divided by number in S.', explanation: 'Event probabilities may be derived theoretically, estimated by relative frequency, or assigned through a model. They must respect the probability axioms.', example: 'A fair die has three even outcomes among six, so P(even)=3/6=1/2.', practice: 'From a standard 52-card deck, find the probability of drawing an ace.', hint: 'There are 4 aces among 52 cards.', answer: 'P(ace)=4/52=1/13.', quiz: 'When is favorable/total valid?', choices: ['When finite outcomes are equally likely', 'For every continuous model', 'Only when events overlap', 'Only for impossible events'], correctIndex: 0, quizExplanation: 'Unequal outcome probabilities cannot be replaced by simple counts.', examFocus: 'compute theoretical and empirical event probabilities', mistake: 'using outcome counts when outcomes are not equally likely',
  }),
  'probability-and-statistics-topic-15-additive-rules': topic({
    title: 'The addition rule handles unions', definition: 'The addition rule calculates the probability that at least one of two events occurs.', rule: 'P(A union B)=P(A)+P(B)-P(A intersection B).', explanation: 'Adding P(A) and P(B) counts their overlap twice, so the intersection is subtracted once. For disjoint events the intersection probability is zero.', example: 'If P(A)=0.5, P(B)=0.4, and P(A intersection B)=0.2, then P(A union B)=0.7.', practice: 'Given P(A)=0.6, P(B)=0.3, P(A intersection B)=0.1, find P(A union B).', hint: 'Add the two probabilities and subtract the overlap.', answer: 'P(A union B)=0.6+0.3-0.1=0.8.', quiz: 'Why subtract the intersection?', choices: ['It was counted twice', 'It is impossible', 'It equals the union', 'Probabilities must be negative'], correctIndex: 0, quizExplanation: 'The overlap appears once in each individual event probability.', examFocus: 'apply general and mutually exclusive addition rules', mistake: 'using the disjoint shortcut for overlapping events',
  }),
  'probability-and-statistics-topic-16-conditional-probability': topic({
    title: 'Conditioning updates the sample space', definition: 'Conditional probability P(A|B) is the probability of A given that B occurred.', rule: 'P(A|B)=P(A intersection B)/P(B), provided P(B)>0.', explanation: 'Conditioning restricts attention to outcomes in B, then measures which also belong to A. It is central to risk, diagnosis, and sequential experiments.', example: 'If 20 of 50 tested devices are wireless and 5 of those fail, P(fail|wireless)=5/20.', practice: 'If P(A intersection B)=0.12 and P(B)=0.30, find P(A|B).', hint: 'Divide the intersection by the conditioning event.', answer: 'P(A|B)=0.12/0.30=0.40.', quiz: 'What is the denominator of P(A|B)?', choices: ['P(B)', 'P(A)', 'P(A union B)', '1-P(B)'], correctIndex: 0, quizExplanation: 'The condition B becomes the restricted reference set.', examFocus: 'compute and interpret conditional probabilities from tables or formulas', mistake: 'reversing P(A|B) and P(B|A)',
  }),
  'probability-and-statistics-topic-17-independence': topic({
    title: 'Independent events do not change each other', definition: 'Events A and B are independent when knowing one occurred does not change the probability of the other.', rule: 'Independence is equivalent to P(A intersection B)=P(A)P(B).', explanation: 'Independence is a model property, not merely lack of overlap. Nonzero mutually exclusive events are necessarily dependent.', example: 'Two fair coin tosses are independent: P(H then H)=1/2 x 1/2=1/4.', practice: 'If P(A)=0.4, P(B)=0.5, and P(A intersection B)=0.2, are A and B independent?', hint: 'Compare the intersection with P(A)P(B).', answer: 'Yes; 0.4x0.5=0.2.', quiz: 'Which statement establishes independence?', choices: ['P(A intersection B)=P(A)P(B)', 'A intersection B is empty', 'P(A)=P(B)', 'P(A union B)=1'], correctIndex: 0, quizExplanation: 'The product equality is the standard independence criterion.', examFocus: 'test independence using products or conditional probabilities', mistake: 'equating independence with mutual exclusivity',
  }),
  'probability-and-statistics-topic-18-product-rule': topic({
    title: 'The product rule builds joint probabilities', definition: 'The product rule expresses an intersection using a marginal and a conditional probability.', rule: 'P(A intersection B)=P(A)P(B|A)=P(B)P(A|B).', explanation: 'The rule follows directly from conditional probability and extends to sequences by multiplying successive conditional probabilities.', example: 'Drawing two aces without replacement has probability (4/52)(3/51).', practice: 'A bag has 3 red and 2 blue balls. Find the probability of two reds without replacement.', hint: 'Multiply the first-red probability by the conditional second-red probability.', answer: 'P(two reds)=(3/5)(2/4)=3/10.', quiz: 'For independent A and B, the product rule becomes:', choices: ['P(A)P(B)', 'P(A)+P(B)', 'P(A)-P(B)', 'P(A)/P(B)'], correctIndex: 0, quizExplanation: 'Independence makes P(B|A)=P(B).', examFocus: 'calculate joint and sequential probabilities with changing conditions', mistake: 'using the same denominator after sampling without replacement',
  }),
  'probability-and-statistics-topic-19-bayes-rule': topic({
    title: 'Bayes rule reverses a condition', definition: 'Bayes rule updates prior probabilities after observing evidence.', rule: 'P(A|B)=P(B|A)P(A)/P(B), with P(B) found by total probability when needed.', explanation: 'Bayesian updating combines a prior rate with the likelihood of evidence. Base rates matter: a sensitive test can still produce many false positives for a rare condition.', example: 'For groups A1 and A2, P(A1|B)=P(B|A1)P(A1)/[P(B|A1)P(A1)+P(B|A2)P(A2)].', practice: 'If P(A)=0.2, P(B|A)=0.8, and P(B)=0.4, find P(A|B).', hint: 'Multiply likelihood by prior, then divide by evidence probability.', answer: 'P(A|B)=(0.8x0.2)/0.4=0.4.', quiz: 'Which quantity is the prior in P(A|B)?', choices: ['P(A)', 'P(B|A)', 'P(A|B)', 'P(B) only'], correctIndex: 0, quizExplanation: 'P(A) describes belief or prevalence before observing B.', examFocus: 'use trees or partitions to compute posterior probabilities', mistake: 'ignoring the prior base rate',
  }),
  'probability-and-statistics-topic-20-random-variables-and-probability-distributions': topic({
    title: 'Random variables assign numbers to outcomes', definition: 'A random variable maps each sample-space outcome to a numerical value; its distribution gives the probabilities of those values.', rule: 'A discrete pmf sums to 1; a continuous pdf integrates to 1 and probabilities are areas.', explanation: 'The distribution, rather than one observed value, describes random behavior. A cumulative distribution F(x)=P(X<=x) works for both discrete and continuous variables.', example: 'For two tosses, X=number of heads has probabilities 1/4, 1/2, 1/4 at 0, 1, 2.', practice: 'For P(X=0)=0.2, P(X=1)=0.5, find P(X=2) if these are the only values.', hint: 'All mass probabilities sum to 1.', answer: 'P(X=2)=1-0.2-0.5=0.3.', quiz: 'What must a valid discrete pmf satisfy?', choices: ['Nonnegative probabilities summing to 1', 'Values summing to 0', 'Equal probabilities only', 'A negative mean'], correctIndex: 0, quizExplanation: 'Probability mass cannot be negative and total mass is one.', examFocus: 'construct, validate, and interpret pmfs, pdfs, and cdfs', mistake: 'confusing random-variable values with their probabilities',
  }),
  'probability-and-statistics-topic-21-mathematical-expectation': topic({
    title: 'Expectation is a probability-weighted average', definition: 'The expectation of g(X) is its long-run probability-weighted average.', rule: 'Discrete: E[g(X)]=sum g(x)p(x); continuous: E[g(X)]=integral g(x)f(x) dx.', explanation: 'Expectation summarizes the center of a distribution or any transformed payoff. Linearity holds whether or not random variables are independent.', example: 'For a fair die, E(X)=(1+2+3+4+5+6)/6=3.5.', practice: 'If X is 0 with probability 0.7 and 10 with probability 0.3, find E(X).', hint: 'Multiply each value by its probability and add.', answer: 'E(X)=0(0.7)+10(0.3)=3.', quiz: 'Which identity always holds?', choices: ['E(aX+b)=aE(X)+b', 'E(X)=P(X)', 'E(X) must be observed', 'E(X) is always an integer'], correctIndex: 0, quizExplanation: 'Expectation is linear under scaling and shifting.', examFocus: 'compute expectations of variables and functions', mistake: 'treating the expected value as the most likely outcome',
  }),
  'probability-and-statistics-topic-22-mean-of-a-random-variable': topic({
    title: 'The distribution mean locates its balance point', definition: 'The mean mu of a random variable is its expected value E(X).', rule: 'mu=sum xp(x) for discrete X or integral x f(x) dx for continuous X.', explanation: 'The mean describes long-run average behavior across repetitions. It can be influenced by extreme values and need not itself be a possible outcome.', example: 'A Bernoulli variable with success probability p has mean p.', practice: 'Find the mean when X has values 1, 2, 3 with probabilities 0.2, 0.5, 0.3.', hint: 'Form the weighted sum.', answer: 'mu=1(0.2)+2(0.5)+3(0.3)=2.1.', quiz: 'What is the mean of Bernoulli(p)?', choices: ['p', '1-p', 'p(1-p)', 'sqrt(p)'], correctIndex: 0, quizExplanation: 'E(X)=0(1-p)+1(p)=p.', examFocus: 'calculate and interpret distribution means', mistake: 'using an unweighted average when outcomes have unequal probabilities',
  }),
  'probability-and-statistics-topic-23-variance-and-covariance-of-random-variables': topic({
    title: 'Variance and covariance describe spread and co-movement', definition: 'Variance measures squared deviation from a mean; covariance measures joint linear deviation.', rule: 'Var(X)=E(X^2)-[E(X)]^2 and Cov(X,Y)=E(XY)-E(X)E(Y).', explanation: 'Variance is nonnegative and has squared units. Covariance sign indicates whether variables tend to move together or oppositely, but its magnitude depends on units.', example: 'If E(X)=2 and E(X^2)=6, then Var(X)=6-4=2.', practice: 'Given E(X)=3 and E(X^2)=13, find Var(X).', hint: 'Subtract the square of the mean from the second moment.', answer: 'Var(X)=13-9=4.', quiz: 'If X and Y are independent, what is Cov(X,Y)?', choices: ['0', '1', 'Var(X)+Var(Y)', 'Always negative'], correctIndex: 0, quizExplanation: 'Independence makes E(XY)=E(X)E(Y).', examFocus: 'compute variance, standard deviation, and covariance', mistake: 'assuming zero covariance always proves independence',
  }),
  'probability-and-statistics-topic-24-means-and-variances-of-linear-combinations-of-random-variables': topic({
    title: 'Linear combinations propagate moments predictably', definition: 'A linear combination has the form aX+bY+c.', rule: 'E(aX+bY+c)=aE(X)+bE(Y)+c; Var(aX+bY)=a^2Var(X)+b^2Var(Y)+2abCov(X,Y).', explanation: 'Means combine linearly without independence. Variance uses squared coefficients and includes covariance; the covariance term vanishes for independent variables.', example: 'For independent X,Y with variances 2 and 3, Var(2X-Y)=4(2)+3=11.', practice: 'Independent X,Y have variances 4 and 9. Find Var(X+2Y).', hint: 'Square the coefficient 2.', answer: 'Var(X+2Y)=4+4(9)=40.', quiz: 'Which term is omitted only when X and Y are uncorrelated?', choices: ['2abCov(X,Y)', 'aE(X)', 'bE(Y)', 'The constant c'], correctIndex: 0, quizExplanation: 'Covariance controls the cross contribution to variance.', examFocus: 'derive means and variances of sums and differences', mistake: 'forgetting to square coefficients in variance calculations',
  }),
  'probability-and-statistics-topic-25-chebyshevs-theorem': topic({
    title: 'Chebyshev gives a distribution-free bound', definition: 'Chebyshev theorem bounds how much probability can lie far from the mean for any finite-variance distribution.', rule: 'P(|X-mu|<k sigma)>=1-1/k^2 for k>1.', explanation: 'The bound needs no normality assumption and is therefore conservative. It guarantees a minimum proportion within a specified number of standard deviations.', example: 'At least 1-1/4=75% of values lie within 2 standard deviations of the mean.', practice: 'What minimum proportion lies within 3 standard deviations?', hint: 'Compute 1-1/3^2.', answer: 'At least 1-1/9=8/9, about 88.9%.', quiz: 'Chebyshev theorem requires:', choices: ['A finite variance', 'A normal distribution', 'A symmetric distribution', 'Discrete data only'], correctIndex: 0, quizExplanation: 'The theorem applies broadly whenever mean and finite variance exist.', examFocus: 'apply and interpret the k-standard-deviation bound', mistake: 'reporting the lower bound as an exact percentage',
  }),
  'probability-and-statistics-topic-26-discrete-probability-distributions': topic({
    title: 'Discrete distributions model counts', definition: 'A discrete distribution assigns probability mass to countable values.', rule: 'Common models include Bernoulli, binomial, geometric, and Poisson, each with specific assumptions.', explanation: 'Selecting a model requires matching the experiment: binomial counts independent fixed-probability successes in n trials; Poisson counts events over exposure.', example: 'For X~Binomial(5,0.2), P(X=0)=0.8^5.', practice: 'For X~Binomial(3,0.5), find P(X=2).', hint: 'Use C(3,2)(0.5)^2(0.5).', answer: 'P(X=2)=3/8=0.375.', quiz: 'Which model counts successes in fixed independent trials?', choices: ['Binomial', 'Uniform continuous', 'Normal only', 't distribution'], correctIndex: 0, quizExplanation: 'The binomial assumptions specify fixed n, independent trials, and constant p.', examFocus: 'identify and calculate with standard discrete models', mistake: 'using a binomial model when success probability changes between trials',
  }),
  'probability-and-statistics-topic-27-continuous-probability-distributions': topic({
    title: 'Continuous probabilities are areas', definition: 'A continuous distribution is described by a nonnegative density whose total area is one.', rule: 'P(a<X<b)=integral from a to b of f(x) dx, while P(X=x)=0.', explanation: 'Uniform, exponential, and normal distributions model different continuous shapes. The density height is not itself a probability.', example: 'For Uniform(0,10), P(2<X<5)=(5-2)/10=0.3.', practice: 'If X~Uniform(0,8), find P(X<2).', hint: 'Use favorable interval length divided by total length.', answer: 'P(X<2)=2/8=0.25.', quiz: 'What does area under a density over all real values equal?', choices: ['1', '0', 'The mean', 'The density maximum'], correctIndex: 0, quizExplanation: 'A density distributes total probability one.', examFocus: 'calculate interval probabilities and choose continuous models', mistake: 'calling f(x) the probability at x',
  }),
  'probability-and-statistics-topic-28-fundamental-sampling-distributions-and-data-descriptions': topic({
    title: 'Data summaries connect to sampling distributions', definition: 'A data description summarizes one sample; a sampling distribution describes a statistic across repeated samples.', rule: 'Center, spread, shape, and unusual values should accompany numerical summaries.', explanation: 'Histograms, boxplots, means, medians, variances, and quartiles describe observed data. Sampling distributions then quantify how those summaries vary under repetition.', example: 'A right-skewed income sample is often better centered by the median and spread by the IQR.', practice: 'For data 1,2,3,4,10, find the median and range.', hint: 'Use the middle value and maximum minus minimum.', answer: 'Median=3 and range=10-1=9.', quiz: 'Which pair is resistant to outliers?', choices: ['Median and IQR', 'Mean and range', 'Mean and variance', 'Maximum and variance'], correctIndex: 0, quizExplanation: 'Median and quartiles depend on order rather than extreme magnitudes.', examFocus: 'describe distributions and distinguish sample from sampling distributions', mistake: 'using only a mean without checking shape and outliers',
  }),
  'probability-and-statistics-topic-29-random-sampling': topic({
    title: 'Random samples support probability-based inference', definition: 'A random sample X1,...,Xn consists of independent observations from the same population distribution.', rule: 'Under iid sampling, E(sample mean)=mu and Var(sample mean)=sigma^2/n.', explanation: 'Random selection makes inclusion probabilistic and supports a sampling distribution. Independence can fail when sampling a substantial fraction without replacement unless adjusted.', example: 'Randomly drawing registered IDs and measuring each selected student approximates iid sampling.', practice: 'If population variance is 25 and n=100 iid observations are sampled, find Var(sample mean).', hint: 'Divide sigma squared by n.', answer: 'Var(sample mean)=25/100=0.25.', quiz: 'What does iid mean?', choices: ['Independent and identically distributed', 'Integer and indexed data', 'Identical interval design', 'Independent irregular deviations'], correctIndex: 0, quizExplanation: 'Each observation follows the same distribution and is independent of the others.', examFocus: 'state random-sample assumptions and implications', mistake: 'calling haphazard or convenience selection random',
  }),
  'probability-and-statistics-topic-30-sampling-distributions': topic({
    title: 'A statistic has its own distribution', definition: 'A sampling distribution is the probability distribution of a statistic over all possible samples of a fixed design and size.', rule: 'Bias concerns its center; standard error is its standard deviation.', explanation: 'Sampling distributions explain why estimates differ from sample to sample. They are the foundation of margins of error, confidence intervals, and tests.', example: 'The distribution of all sample proportions from samples of size 100 is the sampling distribution of p-hat.', practice: 'If an estimator has sampling standard deviation 0.04, what is its standard error?', hint: 'Standard error names the sampling standard deviation.', answer: 'The standard error is 0.04.', quiz: 'What varies in a sampling distribution?', choices: ['The statistic across samples', 'The fixed population parameter', 'Only measurement units', 'The study title'], correctIndex: 0, quizExplanation: 'The parameter is fixed; repeated random samples yield varying statistics.', examFocus: 'identify center, bias, variability, and standard error', mistake: 'confusing the data distribution with the statistic distribution',
  }),
  'probability-and-statistics-topic-31-sampling-distribution-of-means': topic({
    title: 'Sample means become more precise with n', definition: 'The sampling distribution of the sample mean describes its value over repeated samples.', rule: 'E(Xbar)=mu and SE(Xbar)=sigma/sqrt(n) for iid sampling.', explanation: 'Increasing sample size reduces the standard error at a square-root rate. If the population is normal, the sample mean is exactly normal; otherwise it is often approximately normal for large n.', example: 'With sigma=12 and n=36, SE(Xbar)=12/6=2.', practice: 'A population has mean 50 and sigma 10. For n=25, give the mean and SE of Xbar.', hint: 'The mean stays mu; divide sigma by sqrt(n).', answer: 'Mean=50 and SE=10/5=2.', quiz: 'What happens to SE when n is multiplied by 4?', choices: ['It is halved', 'It doubles', 'It is unchanged', 'It becomes zero'], correctIndex: 0, quizExplanation: 'The denominator sqrt(n) doubles.', examFocus: 'calculate probabilities and standard errors for sample means', mistake: 'dividing sigma by n instead of sqrt(n)',
  }),
  'probability-and-statistics-topic-32-central-limit-theorem': topic({
    title: 'The CLT explains approximate normality', definition: 'The central limit theorem states that a standardized sum or mean approaches a normal distribution as sample size grows under suitable conditions.', rule: 'Z=(Xbar-mu)/(sigma/sqrt(n)) is approximately standard normal for sufficiently large n.', explanation: 'The CLT concerns the sampling distribution of the mean, not the raw population. More skewed or heavy-tailed populations usually require larger samples.', example: 'Even for right-skewed service times, the mean of a large random sample can be approximately normal.', practice: 'For mu=100, sigma=20, n=100, standardize Xbar=104.', hint: 'The standard error is 20/sqrt(100)=2.', answer: 'Z=(104-100)/2=2.', quiz: 'What becomes approximately normal under the CLT?', choices: ['The standardized sample mean', 'Every raw observation', 'The population itself', 'Every small sample'], correctIndex: 0, quizExplanation: 'The theorem describes sums and means across repeated samples.', examFocus: 'state conditions and use normal approximations for means', mistake: 'claiming the CLT makes the underlying data normal',
  }),
  'probability-and-statistics-topic-33-sampling-distribution-of-s2': topic({
    title: 'Sample variance links to chi-square', definition: 'S squared is the unbiased sample variance based on squared deviations from the sample mean.', rule: 'For a normal population, (n-1)S^2/sigma^2 follows chi-square with n-1 degrees of freedom.', explanation: 'The chi-square relationship supports confidence intervals and tests for a normal population variance. The distribution is right-skewed, especially at small degrees of freedom.', example: 'For n=11, the variance pivot has 10 degrees of freedom.', practice: 'A normal sample has n=16. What are the degrees of freedom for the S squared pivot?', hint: 'Use n-1.', answer: 'The degrees of freedom are 15.', quiz: 'Which reference distribution applies to (n-1)S^2/sigma^2?', choices: ['Chi-square', 'Standard normal', 'Uniform', 'Binomial'], correctIndex: 0, quizExplanation: 'Normal sampling gives the stated chi-square pivot.', examFocus: 'form the variance pivot and identify degrees of freedom', mistake: 'using n degrees of freedom instead of n-1',
  }),
  'probability-and-statistics-topic-34-t-distribution': topic({
    title: 'The t distribution accounts for estimated scale', definition: 'Student t is a symmetric bell-shaped distribution with heavier tails than the normal.', rule: 'For normal data with unknown sigma, T=(Xbar-mu)/(S/sqrt(n)) follows t with n-1 degrees of freedom.', explanation: 'Replacing sigma with sample standard deviation adds uncertainty, producing heavier tails. As degrees of freedom increase, t approaches standard normal.', example: 'A one-sample mean analysis with n=20 uses t with 19 degrees of freedom.', practice: 'For Xbar=12, mu0=10, S=4, n=16, compute t.', hint: 'The estimated standard error is 4/4=1.', answer: 't=(12-10)/1=2.', quiz: 'Compared with standard normal, a small-df t distribution has:', choices: ['Heavier tails', 'No center', 'Only positive values', 'Zero variance'], correctIndex: 0, quizExplanation: 'Extra scale uncertainty puts more probability in the tails.', examFocus: 'calculate t statistics and choose degrees of freedom', mistake: 'using z critical values when sigma is unknown and n is small',
  }),
  'probability-and-statistics-topic-35-f-quantile-and-probability-plots': topic({
    title: 'F quantiles and probability plots assess variation and fit', definition: 'An F distribution models a ratio of independent scaled variances; a probability plot compares ordered data with theoretical quantiles.', rule: 'For normal independent samples, (S1^2/sigma1^2)/(S2^2/sigma2^2) follows F(df1,df2).', explanation: 'F distributions are positive and right-skewed. In a normal probability plot, an approximately straight pattern supports normality; curvature or isolated points indicate departures.', example: 'S1^2/S2^2=18/9=2 compares two sample variances before reference to F critical values.', practice: 'Compute the variance ratio when S1 squared=12 and S2 squared=4.', hint: 'Place the first variance in the numerator.', answer: 'The F ratio is 12/4=3.', quiz: 'What pattern supports normality on a normal probability plot?', choices: ['Approximately a straight line', 'A perfect circle', 'A horizontal line only', 'Random category labels'], correctIndex: 0, quizExplanation: 'Matching empirical and normal quantiles produces near-linearity.', examFocus: 'read F quantiles and interpret probability plots', mistake: 'treating small plot deviations as automatic proof of nonnormality',
  }),
  'probability-and-statistics-topic-36-single-sample-estimation-problems': topic({
    title: 'Estimate one population parameter', definition: 'Single-sample estimation uses one sample to obtain a point estimate and confidence interval for a population quantity.', rule: 'For an unknown mean with unknown sigma, Xbar +/- t* S/sqrt(n) under appropriate conditions.', explanation: 'Confidence level controls long-run interval coverage, while margin of error combines a critical value and standard error. Conditions and units belong in the conclusion.', example: 'Xbar=20, SE=2, t*=2.1 gives 20 +/- 4.2, or (15.8,24.2).', practice: 'Find a z-based 95% interval for Xbar=50 with known SE=3 using z*=1.96.', hint: 'Compute 50 +/- 1.96(3).', answer: 'The interval is approximately (44.12,55.88).', quiz: 'What directly narrows a confidence interval, all else fixed?', choices: ['A larger sample size', 'A higher confidence level', 'A larger standard deviation', 'A larger critical value'], correctIndex: 0, quizExplanation: 'Larger n reduces standard error.', examFocus: 'construct and interpret intervals for one mean or proportion', mistake: 'saying a fixed computed interval has a probability of containing the parameter',
  }),
  'probability-and-statistics-topic-37-one-and-two-sample-estimation-problems': topic({
    title: 'Match estimation to the comparison', definition: 'One-sample intervals estimate one parameter; two-sample intervals estimate a difference or ratio between populations.', rule: 'Independent means use Xbar1-Xbar2 with combined standard error; paired data use a one-sample interval on differences.', explanation: 'Design determines the method. Independent groups require independence within and between samples; matched pairs preserve pairing by analyzing within-pair differences.', example: 'Before/after scores for the same students are paired, so estimate the mean of after-minus-before differences.', practice: 'Are test scores from the same 12 students before and after tutoring paired or independent?', hint: 'Each after value is naturally linked to one before value.', answer: 'They are paired observations.', quiz: 'What parameter does a two-independent-mean interval target?', choices: ['mu1-mu2', 'mu1+mu2 only', 'One sample median only', 'A single observation'], correctIndex: 0, quizExplanation: 'The statistic Xbar1-Xbar2 estimates the population mean difference.', examFocus: 'choose one-sample, independent two-sample, or paired procedures', mistake: 'treating paired measurements as independent samples',
  }),
  'probability-and-statistics-topic-38-single-sample-tests-of-hypotheses': topic({
    title: 'A hypothesis test evaluates one parameter claim', definition: 'A hypothesis test compares sample evidence with a null claim about a population parameter.', rule: 'Test statistic=(estimate-null value)/standard error; reject H0 when the evidence is sufficiently incompatible at level alpha.', explanation: 'State null and alternative hypotheses before calculation, verify assumptions, compute a statistic and p-value, then conclude in context without claiming proof.', example: 'To test a claimed mean of 100, set H0:mu=100 and choose a one- or two-sided alternative.', practice: 'Write hypotheses for testing whether a mean exceeds 50.', hint: 'The equality belongs in the null.', answer: 'H0: mu=50; Ha: mu>50.', quiz: 'What is a Type I error?', choices: ['Rejecting a true null', 'Failing to reject a false null', 'Computing a sample mean', 'Choosing a larger sample'], correctIndex: 0, quizExplanation: 'The Type I error rate is controlled by alpha.', examFocus: 'state hypotheses, test statistic, p-value, decision, and contextual conclusion', mistake: 'accepting H0 as proven when it is not rejected',
  }),
  'probability-and-statistics-topic-39-one-and-two-sample-tests-of-hypotheses': topic({
    title: 'Tests compare one or two populations', definition: 'One-sample tests compare a parameter with a benchmark; two-sample tests compare parameters across groups.', rule: 'For independent means, t=(Xbar1-Xbar2-null difference)/SE; paired tests instead analyze pair differences.', explanation: 'The alternative determines one- or two-sided evidence. Procedure choice depends on response type, number of groups, independence, pairing, and variance assumptions.', example: 'Testing whether two teaching methods have different mean scores uses Ha:mu1-mu2 is not 0.', practice: 'Write the alternative for testing whether population 1 has a lower mean than population 2.', hint: 'Express the direction using mu1-mu2.', answer: 'Ha: mu1-mu2<0.', quiz: 'Which design calls for a paired t test?', choices: ['The same subjects measured twice', 'Two unrelated random groups', 'One categorical count only', 'Three independent groups'], correctIndex: 0, quizExplanation: 'Repeated measurements create natural pairs.', examFocus: 'select and execute the appropriate one- or two-sample test', mistake: 'ignoring dependence created by matching or repeated measurement',
  }),
  'probability-and-statistics-topic-40-use-of-p-values-for-decision-making-in-testing-hypotheses': topic({
    title: 'The p-value measures incompatibility with H0', definition: 'A p-value is the probability, assuming H0, of a test statistic at least as extreme in the alternative direction as observed.', rule: 'Reject H0 at significance level alpha when p<=alpha; otherwise fail to reject H0.', explanation: 'A p-value is computed under the null model. It is not the probability that H0 is true and does not measure practical importance.', example: 'With p=0.03 and alpha=0.05, reject H0; at alpha=0.01, do not reject.', practice: 'State the decision for p=0.08 at alpha=0.05.', hint: 'Compare p directly with alpha.', answer: 'Fail to reject H0 because 0.08>0.05.', quiz: 'A p-value is calculated assuming:', choices: ['The null hypothesis is true', 'The alternative is certainly true', 'The sample has no variation', 'The effect is important'], correctIndex: 0, quizExplanation: 'It is a tail probability under the null model.', examFocus: 'interpret p-values and make alpha-based decisions', mistake: 'calling the p-value the probability that H0 is true',
  }),
  'probability-and-statistics-topic-41-single-sample-and-one-two-sample-tests': topic({
    title: 'Choose a test from the design and parameter', definition: 'Single-, one-, and two-sample procedures test means, proportions, variances, or differences using the matching sampling model.', rule: 'Identify response type, parameter, number of samples, independence or pairing, assumptions, and alternative before selecting a statistic.', explanation: 'A reliable solution is a workflow rather than a memorized formula: define parameters, state hypotheses, verify conditions, calculate, decide, and conclude in context.', example: 'One observed proportion versus a target uses a one-proportion z test; two independent proportions use a two-proportion z test.', practice: 'Which test fits two independent groups with a quantitative response and unknown population standard deviations?', hint: 'The target is a difference of two means.', answer: 'Use an independent two-sample t test, subject to its conditions.', quiz: 'What should determine test selection first?', choices: ['Study design and parameter', 'The desired conclusion', 'Whichever gives the smallest p-value', 'The order of rows'], correctIndex: 0, quizExplanation: 'The design and estimand determine the valid sampling distribution.', examFocus: 'select among common mean, proportion, and variance tests', mistake: 'choosing a test after looking for a favorable result',
  }),
  'probability-and-statistics-topic-42-linear-regression-and-correlation': topic({
    title: 'Regression models a linear mean relationship', definition: 'Simple linear regression models E(Y|x)=beta0+beta1x; correlation measures standardized linear association.', rule: 'r is between -1 and 1, and in simple regression R^2=r^2.', explanation: 'The slope describes expected response change per unit x. Correlation is unitless and symmetric, while regression distinguishes explanatory and response variables.', example: 'A fitted slope of 2.5 means predicted Y increases 2.5 units for each one-unit increase in x.', practice: 'Interpret the slope in y-hat=10+3x.', hint: 'Describe predicted change in Y for a one-unit increase in x.', answer: 'Predicted Y increases by 3 units for each one-unit increase in x.', quiz: 'What does correlation measure?', choices: ['Strength and direction of linear association', 'Causation', 'Difference in means only', 'Nonlinear fit exclusively'], correctIndex: 0, quizExplanation: 'Correlation summarizes linear co-movement, not causality.', examFocus: 'interpret slope, intercept, correlation, R-squared, and residuals', mistake: 'using correlation as proof of causation',
  }),
  'probability-and-statistics-topic-43-least-squares-and-the-fitted-model': topic({
    title: 'Least squares minimizes residual error', definition: 'A residual is observed minus fitted response; least squares chooses coefficients minimizing the sum of squared residuals.', rule: 'SSE=sum(yi-yhat_i)^2, with yhat=b0+b1x in simple regression.', explanation: 'The fitted line balances residuals algebraically and provides predictions within the data range. Residual plots check linearity, constant variance, and unusual observations.', example: 'If y=8 and y-hat=6.5, the residual is 1.5.', practice: 'An observation is y=12 and its fitted value is 14. Find the residual.', hint: 'Residual equals observed minus fitted.', answer: 'The residual is 12-14=-2.', quiz: 'What quantity does ordinary least squares minimize?', choices: ['Sum of squared residuals', 'Sum of x values', 'Maximum response', 'Correlation sign'], correctIndex: 0, quizExplanation: 'Squaring prevents cancellation and penalizes large residuals.', examFocus: 'calculate fitted values and residuals and diagnose a fitted model', mistake: 'reversing fitted and observed values when computing residuals',
  }),
  'probability-and-statistics-topic-44-multiple-linear-regression': topic({
    title: 'Multiple regression adjusts for several predictors', definition: 'Multiple linear regression models a response mean as a linear combination of two or more predictors.', rule: 'E(Y|x)=beta0+beta1x1+...+betapxp.', explanation: 'Each slope is a partial effect: expected response change for a one-unit predictor increase while other listed predictors are held fixed. Diagnostics and collinearity checks remain essential.', example: 'In y-hat=5+2x1-3x2, the x1 coefficient is 2 conditional on the same x2.', practice: 'For y-hat=1+2x1+4x2, predict at x1=3,x2=2.', hint: 'Substitute both predictor values.', answer: 'y-hat=1+2(3)+4(2)=15.', quiz: 'How is beta1 interpreted?', choices: ['Change in mean Y per unit x1 holding other predictors fixed', 'Change in x1 per unit Y', 'The correlation of all variables', 'Proof that x1 causes Y'], correctIndex: 0, quizExplanation: 'A multiple-regression coefficient is conditional on included predictors.', examFocus: 'interpret partial coefficients, fit, interactions, and diagnostics', mistake: 'giving a marginal interpretation to a partial coefficient',
  }),
  'probability-and-statistics-topic-45-nonlinear-regression-models': topic({
    title: 'Nonlinear models represent curved relationships', definition: 'A nonlinear regression model has a mean response that is not a linear function of its unknown parameters or predictors.', rule: 'Fit a scientifically justified curve, estimate parameters numerically when necessary, and validate with residuals and prediction behavior.', explanation: 'Exponential, logistic, and saturation curves can capture patterns a straight line misses. Some transformations produce a linear form but also change error assumptions.', example: 'Y=ae^(bx)+error represents exponential growth or decay depending on b.', practice: 'Which curve approaches an upper limit: linear, quadratic, or logistic?', hint: 'Think of bounded growth with an S shape.', answer: 'A logistic curve approaches an upper limit.', quiz: 'Why not always use a high-degree polynomial?', choices: ['It may overfit and extrapolate poorly', 'It cannot curve', 'It has no parameters', 'It always gives zero residuals'], correctIndex: 0, quizExplanation: 'Flexible polynomials can chase noise and behave unrealistically outside the data.', examFocus: 'recognize nonlinear forms and assess fit and extrapolation', mistake: 'selecting a curve solely because it fits the observed points closely',
  }),
  'probability-and-statistics-topic-46-linear-regression-model-using-matrices': topic({
    title: 'Matrix notation unifies linear regression', definition: 'The linear model writes all observations as y=X beta+epsilon, where X is the design matrix.', rule: 'When X transpose X is invertible, beta-hat=(X transpose X)^(-1)X transpose y.', explanation: 'Matrix form handles many predictors compactly. The fitted vector is X beta-hat and residual vector is y-X beta-hat; rank conditions ensure unique estimates.', example: 'An intercept column of ones plus one predictor column gives the simple-regression design matrix.', practice: 'What are the dimensions of X for n observations and p coefficients including the intercept?', hint: 'Rows represent observations and columns represent coefficients.', answer: 'X has n rows and p columns.', quiz: 'What condition gives a unique ordinary least-squares solution?', choices: ['X has full column rank', 'All y values are equal', 'X is square only', 'Residuals are all positive'], correctIndex: 0, quizExplanation: 'Full column rank makes X transpose X invertible.', examFocus: 'identify matrix dimensions and derive fitted and residual vectors', mistake: 'omitting the intercept column when the model includes an intercept',
  }),
  'probability-and-statistics-topic-47-properties-of-the-least-squares-estimators': topic({
    title: 'Least-squares estimators have optimal linear properties', definition: 'Under the linear-model assumptions, ordinary least-squares coefficient estimators are linear and unbiased.', rule: 'E(beta-hat)=beta and Var(beta-hat)=sigma^2(X transpose X)^(-1); Gauss-Markov makes OLS BLUE.', explanation: 'BLUE means best, or minimum variance, among linear unbiased estimators under zero-mean uncorrelated constant-variance errors and full rank. Normality is additionally used for exact small-sample t and F inference.', example: 'If errors have mean zero, repeated fitted slopes center on the true slope rather than systematically overshooting it.', practice: 'What does BLUE stand for in the Gauss-Markov theorem?', hint: 'Expand each letter as a property of the estimator.', answer: 'Best Linear Unbiased Estimator.', quiz: 'Which assumption is needed for the usual OLS variance formula?', choices: ['Constant error variance and uncorrelated errors', 'A nonlinear mean', 'Perfect collinearity', 'All residuals equal zero'], correctIndex: 0, quizExplanation: 'Homoscedastic uncorrelated errors yield sigma squared times the inverse information matrix.', examFocus: 'state unbiasedness, variance, BLUE conditions, and the role of normality', mistake: 'claiming Gauss-Markov requires normally distributed errors',
  }),
}
