import { discreteMathematicsTopics } from './discreteMathematics'
import { oopTopics } from './oop'

const seeds = {
  'digital-logic-design': {
    note: { heading: 'Number systems at a glance', explanation: 'A number system gives symbols a place value. Digital systems commonly use binary, while octal and hexadecimal provide compact ways to write binary patterns.', keyPoints: ['Binary uses base 2: digits 0 and 1.', 'Each position represents a power of the base.', 'Group binary digits in threes for octal and fours for hexadecimal.'], example: '1011₂ = 8 + 2 + 1 = 11₁₀.' },
    practice: { prompt: 'Convert 13₁₀ to binary.', hint: 'Find the powers of two that add to 13.', answer: '1101₂', explanation: '13 = 8 + 4 + 1, so the 8, 4, and 1 positions are set.' },
    quiz: { prompt: 'Which base does hexadecimal use?', choices: ['2', '8', '10', '16'], correctIndex: 3, explanation: 'Hexadecimal has sixteen symbols: 0–9 and A–F.' },
  },
  'discrete-mathematics': {
    note: { heading: 'Thinking in sets', explanation: 'A set is a well-defined collection of distinct objects. Set notation lets us describe, combine, and compare collections precisely.', keyPoints: ['Union contains elements from either set.', 'Intersection contains elements common to both.', 'Difference keeps elements in one set but not the other.'], example: 'If A={1,2} and B={2,3}, then A∩B={2}.' },
    practice: { prompt: 'Let A={1,2,3} and B={3,4}. Find A∪B.', hint: 'Include each distinct element that appears in either set.', answer: '{1,2,3,4}', explanation: 'A union lists every element once.' },
    quiz: { prompt: 'Which symbol denotes set intersection?', choices: ['∪', '∩', '⊂', '∅'], correctIndex: 1, explanation: 'The ∩ symbol represents elements shared by both sets.' },
  },
  'expository-writing': {
    note: { heading: 'Start with purpose and audience', explanation: 'Good writing begins before the first draft. Knowing why you are writing and who will read it guides tone, evidence, detail, and structure.', keyPoints: ['Name the outcome you want from the reader.', 'Consider what the audience already knows.', 'Choose details and tone that fit the situation.'], example: 'A technical guide defines terms for beginners but can use shorthand with specialists.' },
    practice: { prompt: 'Write one purpose statement for an email requesting a deadline extension.', hint: 'State the desired outcome and the reason the reader should consider it.', answer: 'My purpose is to request a two-day extension and explain the documented circumstance affecting my work.', explanation: 'The statement identifies both the action and supporting context.' },
    quiz: { prompt: 'Which choice should audience awareness influence?', choices: ['Only spelling', 'Tone and detail', 'Page color only', 'Nothing in a draft'], correctIndex: 1, explanation: 'Audience affects the tone, context, evidence, and amount of explanation.' },
  },
  'ideology-constitution-pakistan': {
    note: { heading: 'What ideology means', explanation: 'An ideology is an organized set of ideas and values that helps a group interpret society and imagine how it should be ordered.', keyPoints: ['It links beliefs with social or political goals.', 'It can shape collective identity.', 'Historical context influences how an ideology develops.'], example: 'A national ideology can connect shared values to a movement for self-determination.' },
    practice: { prompt: 'In one sentence, distinguish an ideology from a single opinion.', hint: 'Think about scope and organization.', answer: 'An ideology is a connected system of beliefs and values, while an opinion is one individual judgment.', explanation: 'Ideologies organize multiple ideas into a broader worldview.' },
    quiz: { prompt: 'An ideology is best described as:', choices: ['One isolated fact', 'A connected system of ideas and values', 'A list of dates', 'Only a legal document'], correctIndex: 1, explanation: 'Ideology connects beliefs, values, and goals into a coherent outlook.' },
  },
  'mathematics-2': {
    note: { heading: 'Functions connect inputs to outputs', explanation: 'A function assigns exactly one output to every input in its domain. Its domain lists allowed inputs; its range describes resulting outputs.', keyPoints: ['Each domain value has one output.', 'Notation f(x) names the output at x.', 'A graph passes the vertical line test when it represents a function.'], example: 'For f(x)=x², f(3)=9.' },
    practice: { prompt: 'If f(x)=2x+1, find f(4).', hint: 'Substitute 4 wherever x appears.', answer: '9', explanation: 'f(4)=2(4)+1=9.' },
    quiz: { prompt: 'What is the domain of f(x)=1/x over real numbers?', choices: ['All real numbers', 'All real numbers except 0', 'Only positive numbers', 'Only integers'], correctIndex: 1, explanation: 'Division by zero is undefined, so zero is excluded.' },
  },
  oop: {
    note: { heading: 'From structures to objects', explanation: 'Object-oriented problem solving groups state and behavior into objects. A class defines the shared blueprint from which objects are created.', keyPoints: ['State is stored in data members.', 'Behavior is expressed through member functions.', 'Encapsulation keeps related data and operations together.'], example: 'A BankAccount class can hold a balance and expose deposit and withdraw operations.' },
    practice: { prompt: 'Name one likely data member and one member function for a Student class.', hint: 'Choose a fact the object stores and an action it performs.', answer: 'Data member: name; member function: enroll(course).', explanation: 'The data member represents state, while the function represents behavior.' },
    quiz: { prompt: 'A class is primarily:', choices: ['A single variable', 'A blueprint for objects', 'A loop', 'A file format'], correctIndex: 1, explanation: 'A class defines the data and operations shared by its objects.' },
  },
  'probability-and-statistics': {
    note: { heading: 'Data, samples, and populations', explanation: 'A population is the entire group of interest. A sample is the subset observed so that we can describe data and make careful inferences about the population.', keyPoints: ['A parameter describes a population.', 'A statistic describes a sample.', 'Representative sampling reduces systematic bias.'], example: 'Surveying 300 selected students can estimate preferences across the university population.' },
    practice: { prompt: 'A researcher measures 50 of 2,000 devices. Identify the sample.', hint: 'The sample is the group actually observed.', answer: 'The 50 measured devices.', explanation: 'All 2,000 devices form the population; the observed 50 form the sample.' },
    quiz: { prompt: 'Which term describes the complete group under study?', choices: ['Sample', 'Variable', 'Population', 'Statistic'], correctIndex: 2, explanation: 'The population is the full group about which a study wants to draw conclusions.' },
  },
}

const expositoryWritingTopics = {
  'expository-writing-topic-1-writing-process': {
    note: { heading: 'Writing is a recursive process', explanation: 'Effective writers plan, draft, revise, edit, and proofread. These stages overlap: new evidence may send a writer back to planning, while revision may require a fresh draft.', keyPoints: ['Definition: revision improves ideas, organization, and support; editing corrects sentences and style; proofreading catches final surface errors.', 'Exam focus: explain the purpose of each stage and distinguish revision from editing.', 'Common mistake: treating the first draft as final or proofreading before the ideas are organized.'], example: 'After drafting an essay, a writer moves a weak reason to the introduction, adds evidence, edits wordy sentences, and finally checks spelling.' },
    practice: { prompt: 'Place these actions in a sensible order: correct spelling, outline ideas, strengthen a weak argument, write a first draft.', hint: 'Separate planning, drafting, revision, and proofreading.', answer: 'Outline ideas; write a first draft; strengthen the argument; correct spelling.', explanation: 'Higher-level decisions come before final surface corrections.' },
    quiz: { prompt: 'Which action is revision rather than proofreading?', choices: ['Fixing a typo', 'Adding evidence to support a claim', 'Correcting capitalization', 'Checking page numbers'], correctIndex: 1, explanation: 'Revision changes meaning and support; proofreading checks final surface details.' },
  },
  'expository-writing-topic-2-purpose-and-audience': {
    note: { heading: 'Purpose and audience guide every choice', explanation: 'Purpose is the result a writer wants to achieve, while audience is the intended reader or group. Together they determine tone, evidence, vocabulary, and level of detail.', keyPoints: ['Definition: tone is the writer\'s attitude as conveyed through language and style.', 'Exam focus: identify purpose and audience, then justify suitable tone and supporting details.', 'Common mistake: using the same vocabulary and background detail for specialists and beginners.'], example: 'A campus safety notice uses direct instructions and plain language; a research report for specialists can use defined technical terms.' },
    practice: { prompt: 'How should a guide to password safety change when written for first-year students rather than cybersecurity professionals?', hint: 'Consider terminology, examples, and assumed knowledge.', answer: 'Use plain language, define technical terms, and give familiar step-by-step examples.', explanation: 'Audience knowledge determines vocabulary and the amount of explanation.' },
    quiz: { prompt: 'A writer\'s purpose primarily answers which question?', choices: ['What result should this text achieve?', 'How many pages are available?', 'Which font looks best?', 'Where was the text printed?'], correctIndex: 0, explanation: 'Purpose states what the writer wants the text to accomplish.' },
  },
  'expository-writing-topic-3-paragraph-writing': {
    note: { heading: 'Build one unified, coherent paragraph', explanation: 'A strong paragraph develops one controlling idea through a topic sentence, relevant supporting details, and a concluding or linking sentence.', keyPoints: ['Definitions: unity means every sentence supports one main idea; coherence means ideas connect in a logical, readable order.', 'Exam focus: write a clear topic sentence and support it with reasons, facts, examples, or explanation.', 'Common mistake: adding an interesting sentence that does not support the controlling idea.'], example: 'Topic sentence: Regular backups protect students from data loss. Supporting sentences can explain device failure, cloud copies, and a weekly backup routine.' },
    practice: { prompt: 'Write a topic sentence for a paragraph explaining two benefits of studying in a group.', hint: 'Name the topic and the controlling idea without listing unrelated points.', answer: 'Studying in a focused group improves both understanding and accountability.', explanation: 'The sentence limits the paragraph to two connected benefits.' },
    quiz: { prompt: 'Which feature means every sentence supports the paragraph\'s main idea?', choices: ['Unity', 'Dialogue', 'Narration', 'Formatting'], correctIndex: 0, explanation: 'Unity keeps all details relevant to one controlling idea.' },
  },
  'expository-writing-topic-4-essay-writing': {
    note: { heading: 'Organize an essay around a thesis', explanation: 'An essay normally contains an introduction with a thesis, body paragraphs that develop its main points, and a conclusion that synthesizes the discussion.', keyPoints: ['Definition: a thesis statement expresses the essay\'s central controlling claim or main idea.', 'Exam focus: create an outline in which each body paragraph clearly advances the thesis.', 'Common mistake: writing a thesis that is only a broad topic or introducing new evidence in the conclusion.'], example: 'Thesis: University coding clubs improve students\' practical skills, peer support, and career awareness.' },
    practice: { prompt: 'Turn the topic “online learning” into a focused explanatory thesis.', hint: 'State a specific main idea and preview useful categories.', answer: 'Online learning succeeds when courses combine clear weekly structure, active practice, and timely feedback.', explanation: 'The thesis is focused and supplies a plan for three body sections.' },
    quiz: { prompt: 'Where should the central controlling idea of an essay appear most clearly?', choices: ['The thesis statement', 'Every citation', 'The page number', 'Only the title'], correctIndex: 0, explanation: 'The thesis states the essay\'s central idea and guides its structure.' },
  },
  'expository-writing-topic-5-descriptive-essays': {
    note: { heading: 'Use selected details to create a dominant impression', explanation: 'A descriptive essay helps readers experience a person, place, object, or event through precise sensory details arranged around one controlling impression.', keyPoints: ['Definitions: imagery appeals to the senses; a dominant impression is the main feeling or view created by the description.', 'Exam focus: select concrete details and organize them spatially, chronologically, or by importance.', 'Common mistake: listing adjectives without using specific nouns, active verbs, or a clear purpose.'], example: 'Instead of “The lab was messy,” write: “Loose wires curled across the benches while cooling fans hummed beneath half-built robots.”' },
    practice: { prompt: 'Revise “The library was quiet” using at least two sensory details.', hint: 'Show what could be heard, seen, or felt.', answer: 'Pages whispered under the warm lamps, and even a dropped pencil sounded sharp against the tiled floor.', explanation: 'Concrete sound and visual details create a focused impression.' },
    quiz: { prompt: 'What unifies the details in a descriptive essay?', choices: ['A dominant impression', 'A bibliography alone', 'Random adjective lists', 'A debate opponent'], correctIndex: 0, explanation: 'A dominant impression guides which sensory details belong.' },
  },
  'expository-writing-topic-6-persuasive-writing': {
    note: { heading: 'Support a debatable claim responsibly', explanation: 'Persuasive writing asks readers to accept a position or take action by combining a clear claim, sound reasons, credible evidence, and fair treatment of counterarguments.', keyPoints: ['Definitions: a claim is the position being argued; a counterargument is a reasonable opposing view; a rebuttal answers it.', 'Exam focus: connect each piece of evidence to the claim and address a relevant counterargument.', 'Common mistake: relying on emotion, exaggeration, or unsupported opinion instead of reasoning and evidence.'], example: 'Claim: The university should extend library hours. Evidence about student schedules supports the reason, while a rebuttal can address staffing costs.' },
    practice: { prompt: 'Give one reason and one type of evidence for the claim that campuses should provide more bicycle parking.', hint: 'Make the evidence measurable or verifiable.', answer: 'Reason: secure parking encourages low-cost transport. Evidence: compare bicycle use and rack occupancy before and after new racks are installed.', explanation: 'The proposed evidence can test the stated reason.' },
    quiz: { prompt: 'What does a rebuttal do?', choices: ['Answers a counterargument', 'Introduces an unrelated topic', 'Repeats the title', 'Removes all evidence'], correctIndex: 0, explanation: 'A rebuttal explains why an opposing point does not defeat the claim.' },
  },
  'expository-writing-topic-7-sentence-errors': {
    note: { heading: 'Recognize and repair sentence boundaries', explanation: 'Complete sentences need an independent clause. Fragments lack a complete independent thought; run-ons join independent clauses incorrectly; faulty agreement makes subjects and verbs inconsistent.', keyPoints: ['Definitions: a comma splice joins independent clauses with only a comma; a fragment is punctuated as a sentence but cannot stand alone.', 'Exam focus: diagnose fragments, fused sentences, comma splices, agreement errors, and misplaced modifiers, then revise them.', 'Common mistake: assuming a long group of words is complete simply because it ends with a period.'], example: 'Comma splice: “The test ended, we left.” Correct: “The test ended, so we left.”' },
    practice: { prompt: 'Correct this sentence: “Because the server stopped responding.”', hint: 'Attach the dependent clause to an independent clause.', answer: 'Because the server stopped responding, the application displayed an error.', explanation: 'The revision completes the thought with an independent clause.' },
    quiz: { prompt: 'What error appears in “The draft was ready, I submitted it”?', choices: ['Comma splice', 'Fragment', 'Subject-verb disagreement', 'Misplaced modifier'], correctIndex: 0, explanation: 'Two independent clauses are joined by only a comma.' },
  },
  'expository-writing-topic-8-how-to-give-presentations': {
    note: { heading: 'Plan a presentation for listeners', explanation: 'An effective presentation has a focused purpose, a clear opening-body-closing structure, selective evidence, readable visual aids, and rehearsal matched to the time limit.', keyPoints: ['Definition: a signpost is a verbal cue that shows where the talk is going, such as “First” or “To conclude.”', 'Exam focus: explain planning, slide design, rehearsal, timing, and preparation for questions.', 'Common mistake: placing full paragraphs on slides and reading them word for word.'], example: 'A five-minute talk may use an opening question, three clearly signposted points with one diagram, and a brief concluding takeaway.' },
    practice: { prompt: 'Create a three-part outline for a short presentation on responsible social-media use.', hint: 'Include an opening, a limited body, and a closing takeaway.', answer: 'Opening: a privacy scenario; body: verify information, protect personal data, communicate respectfully; closing: pause and check before posting.', explanation: 'The outline is focused, ordered, and easy for listeners to follow.' },
    quiz: { prompt: 'Which slide practice best supports an audience?', choices: ['Use concise text and relevant visuals', 'Fill every slide with paragraphs', 'Read every word without looking up', 'Use decorative animation on every line'], correctIndex: 0, explanation: 'Concise, relevant visuals support rather than compete with the speaker.' },
  },
  'expository-writing-topic-9-oral-presentations': {
    note: { heading: 'Deliver ideas clearly and confidently', explanation: 'Oral delivery depends on intelligible voice, suitable pace and volume, purposeful pauses, audience contact, natural gestures, and recovery strategies for nervousness.', keyPoints: ['Definitions: articulation is clear production of speech sounds; vocal variety changes pace, pitch, volume, and emphasis to convey meaning.', 'Exam focus: discuss verbal and nonverbal delivery, audience engagement, and question handling.', 'Common mistake: speaking too quickly, avoiding eye contact, or memorizing so rigidly that delivery sounds mechanical.'], example: 'A speaker pauses after a key result, looks across the room, stresses the conclusion, and paraphrases a question before answering it.' },
    practice: { prompt: 'Name two delivery changes that would help a speaker who rushes and sounds monotonous.', hint: 'Consider pace, pauses, stress, pitch, and rehearsal.', answer: 'Mark pauses between ideas and vary stress or pitch on key words while rehearsing with a timer.', explanation: 'Pauses improve pace; vocal variety makes important ideas audible.' },
    quiz: { prompt: 'Which behavior most directly improves connection with listeners?', choices: ['Regular audience eye contact', 'Reading only from the screen', 'Turning toward the projector', 'Speaking without pauses'], correctIndex: 0, explanation: 'Appropriate eye contact helps speakers monitor and engage the audience.' },
  },
  'expository-writing-topic-10-comparison-and-contrast-essays': {
    note: { heading: 'Compare subjects using consistent criteria', explanation: 'A comparison-and-contrast essay explains meaningful similarities and differences between subjects that share a useful basis for comparison.', keyPoints: ['Definitions: block organization discusses all points for one subject before the other; point-by-point organization treats both subjects under each criterion.', 'Exam focus: state the basis of comparison, use parallel criteria, and choose one consistent organization.', 'Common mistake: describing two subjects separately without explaining why their similarities or differences matter.'], example: 'A point-by-point essay can compare online and classroom learning by flexibility, interaction, and access to resources.' },
    practice: { prompt: 'Propose three parallel criteria for comparing printed and digital textbooks.', hint: 'Each criterion must apply fairly to both subjects.', answer: 'Portability, annotation experience, and long-term cost.', explanation: 'All three criteria can be examined for both formats.' },
    quiz: { prompt: 'In point-by-point organization, what does each body section discuss?', choices: ['Both subjects under one criterion', 'Only one entire subject', 'An unrelated example', 'Only the conclusion'], correctIndex: 0, explanation: 'Point-by-point structure compares both subjects criterion by criterion.' },
  },
  'expository-writing-topic-11-dialogue-writing': {
    note: { heading: 'Make dialogue purposeful and readable', explanation: 'Dialogue records spoken exchanges to reveal character, convey information, or advance action. Effective dialogue sounds natural but removes the repetition and filler of ordinary speech.', keyPoints: ['Definitions: a dialogue tag identifies the speaker; subtext is meaning implied rather than directly stated.', 'Exam focus: punctuate quoted speech, start a new paragraph for each speaker, and give every exchange a purpose.', 'Common mistake: making every character sound identical or using dialogue only to deliver background information.'], example: '“You saved the file, right?” Sana asked. Ali stared at the blank screen. “I thought you did.”' },
    practice: { prompt: 'Write two lines of dialogue that imply, without directly stating, that a project is late.', hint: 'Use a deadline reference or reaction as subtext.', answer: '“The client meeting starts at nine,” Mira said. Hamza looked at the unfinished slides. “Then we have a long night.”', explanation: 'The situation and response imply lateness without explaining it directly.' },
    quiz: { prompt: 'What formatting usually marks a change of speaker?', choices: ['A new paragraph', 'A footnote', 'A new title page', 'A semicolon after every line'], correctIndex: 0, explanation: 'Starting a new paragraph helps readers track who is speaking.' },
  },
  'expository-writing-topic-12-short-story-writing': {
    note: { heading: 'Shape character and conflict into a complete arc', explanation: 'A short story compresses character, setting, conflict, plot, point of view, and theme into a limited space where selected details contribute to one central effect.', keyPoints: ['Definitions: conflict is the central struggle; climax is the point of greatest tension or decisive change; resolution shows the outcome.', 'Exam focus: establish a clear conflict, develop cause-and-effect events, and use a consistent point of view.', 'Common mistake: beginning with excessive background or resolving the conflict through an unexplained coincidence.'], example: 'A student must recover a corrupted project before a demonstration; each failed attempt increases pressure until a backup is found and tested.' },
    practice: { prompt: 'Create a one-sentence conflict and a plausible climax for a story about a lost phone.', hint: 'Make the climax result from the character\'s choices.', answer: 'Conflict: A traveler loses a phone containing the only copy of an important recording. Climax: After tracing a clue in a cloud login alert, the traveler confronts the finder at the bus terminal.', explanation: 'The climax grows from the established problem and an earlier clue.' },
    quiz: { prompt: 'Which plot moment usually contains the greatest tension or decisive change?', choices: ['Climax', 'Title', 'Setting description', 'Dialogue tag'], correctIndex: 0, explanation: 'The climax is the story\'s peak conflict or turning point.' },
  },
  'expository-writing-topic-13-review-writing': {
    note: { heading: 'Evaluate a work with clear criteria', explanation: 'A review briefly identifies and summarizes a work, states an overall judgment, and supports that judgment with specific evidence and relevant evaluative criteria.', keyPoints: ['Definitions: criteria are standards used for judgment; evaluation explains how well a work meets those standards.', 'Exam focus: balance concise summary with evidence-based analysis and a qualified recommendation.', 'Common mistake: retelling the entire work or offering praise and criticism without examples.'], example: 'A software review may assess usability, reliability, and value, citing specific interface features or test results for each criterion.' },
    practice: { prompt: 'Write an evaluative claim about a film using one named criterion.', hint: 'State a judgment and the standard behind it.', answer: 'The film builds suspense effectively because its pacing steadily shortens the time between each new obstacle.', explanation: 'The claim names pacing as a criterion and indicates evidence to discuss.' },
    quiz: { prompt: 'What distinguishes a review from a plot summary?', choices: ['A supported evaluation', 'A longer title', 'More character names', 'The absence of criteria'], correctIndex: 0, explanation: 'A review judges the work using criteria and evidence.' },
  },
  'expository-writing-topic-14-narrative-essays': {
    note: { heading: 'Use a focused experience to communicate significance', explanation: 'A narrative essay presents connected events, often from personal experience, while using scene, reflection, and a clear sequence to develop a central insight.', keyPoints: ['Definitions: chronological order follows time; reflection explains the meaning or significance of narrated events.', 'Exam focus: select a focused event, build a clear sequence and turning point, then connect it to an insight.', 'Common mistake: listing events without scene details, transitions, or reflection on why the experience matters.'], example: 'An essay about a failed demonstration can narrate the tense moments, the recovery decision, and the lesson about testing backups.' },
    practice: { prompt: 'Write a reflective sentence that could conclude a narrative about getting lost on the first day of university.', hint: 'Explain what the experience changed or taught.', answer: 'By asking for help, I learned that confidence is not knowing every route but being willing to find one.', explanation: 'The sentence turns the event into a clear insight.' },
    quiz: { prompt: 'Which element explains why a narrated experience matters?', choices: ['Reflection', 'Page numbering', 'A random flashback', 'A works-cited heading'], correctIndex: 0, explanation: 'Reflection connects events to the narrative\'s larger insight.' },
  },
  'expository-writing-topic-15-letter-writing': {
    note: { heading: 'Match letter form and tone to the situation', explanation: 'Letters communicate a specific message to a named reader. Formal letters use standard structure, precise subject matter, courteous tone, and an explicit request or next step.', keyPoints: ['Definitions: salutation opens the letter to the recipient; complimentary close is the courteous closing before the signature.', 'Exam focus: use the correct address, date, salutation, body, close, and tone for formal or informal purpose.', 'Common mistake: mixing casual language with a formal request or failing to state the requested action clearly.'], example: 'A formal complaint identifies the purchase, describes the defect objectively, supplies evidence, and requests a replacement by a reasonable date.' },
    practice: { prompt: 'Write a courteous closing request for a letter asking the registrar to correct a transcript error.', hint: 'State the action and identify useful supporting material.', answer: 'Please correct the course grade on my transcript; I have enclosed the signed result sheet for verification.', explanation: 'The request is specific, courteous, and supported by evidence.' },
    quiz: { prompt: 'Which feature is most important in a formal request letter?', choices: ['A clear requested action', 'Slang and emojis', 'An unrelated anecdote', 'An omitted recipient'], correctIndex: 0, explanation: 'The recipient should be able to identify exactly what response is requested.' },
  },
  'expository-writing-topic-16-public-speaking': {
    note: { heading: 'Speak ethically to inform, persuade, or commemorate', explanation: 'Public speaking is planned communication to an audience. Strong speeches combine audience analysis, credible support, clear organization, ethical source use, effective delivery, and adaptation to feedback.', keyPoints: ['Definitions: credibility is the audience\'s judgment of a speaker\'s competence and trustworthiness; feedback is the audience response used to adapt delivery.', 'Exam focus: explain audience analysis, speech structure, supporting evidence, delivery, ethics, and anxiety management.', 'Common mistake: making unsupported claims, ignoring time limits, or confusing confident delivery with speaking as loudly as possible.'], example: 'A persuasive campus speech cites reliable transport data, acknowledges cost concerns, proposes a feasible action, and ends with a direct call to action.' },
    practice: { prompt: 'Draft a specific-purpose statement for a three-minute speech encouraging classmates to verify online information.', hint: 'Name the audience and the response you want.', answer: 'By the end of my speech, classmates should be able to use three quick checks before sharing an online claim.', explanation: 'The statement defines the audience, outcome, and achievable scope.' },
    quiz: { prompt: 'Which practice most strengthens a public speaker\'s credibility?', choices: ['Using accurate evidence and acknowledging sources', 'Hiding weak evidence', 'Ignoring counterarguments', 'Exceeding the time limit'], correctIndex: 0, explanation: 'Accuracy and ethical source acknowledgment demonstrate competence and trustworthiness.' },
  },
}

export function getSeed(subjectSlug, activeTopicId, firstTopicId) {
  if (subjectSlug === 'expository-writing') return expositoryWritingTopics[activeTopicId] ?? null
  if (subjectSlug === 'discrete-mathematics') return discreteMathematicsTopics[activeTopicId] ?? null
  if (subjectSlug === 'oop') return oopTopics[activeTopicId] ?? null
  return activeTopicId === firstTopicId ? seeds[subjectSlug] : null
}
