// Generated by scripts/build-syllabus-data.mjs. Do not edit.
export const curricula = Object.freeze({
  "digital-logic-design": {
    "subjectSlug": "digital-logic-design",
    "units": [
      {
        "id": "digital-logic-design-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "digital-logic-design-topic-1-introduction",
            "title": "Introduction"
          },
          {
            "id": "digital-logic-design-topic-2-number-systems-binary-octal-hexadecimal",
            "title": "Number Systems: Binary, Octal, Hexadecimal"
          },
          {
            "id": "digital-logic-design-topic-3-number-ranges",
            "title": "Number Ranges"
          },
          {
            "id": "digital-logic-design-topic-4-arithmetic-operations",
            "title": "Arithmetic Operations"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "digital-logic-design-topic-5-conversion-from-decimal-to-other-bases",
            "title": "Conversion from Decimal to Other Bases"
          }
        ],
        "assessments": [
          "Assignment #01"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "digital-logic-design-topic-6-negative-number-representations",
            "title": "Negative Number Representations"
          }
        ],
        "assessments": [
          "Quiz #01"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "digital-logic-design-topic-7-binary-logic-and-gates",
            "title": "Binary Logic and Gates"
          },
          {
            "id": "digital-logic-design-topic-8-boolean-algebra",
            "title": "Boolean Algebra"
          },
          {
            "id": "digital-logic-design-topic-9-standard-forms",
            "title": "Standard Forms"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "digital-logic-design-topic-10-sop-and-pos",
            "title": "SOP and POS"
          },
          {
            "id": "digital-logic-design-topic-11-expressing-functions-from-one-form-into-another",
            "title": "Expressing functions from one form into another"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "digital-logic-design-topic-12-k-maps-sop-pos",
            "title": "K-maps: SOP, POS"
          },
          {
            "id": "digital-logic-design-topic-13-manipulating-maps",
            "title": "Manipulating maps"
          },
          {
            "id": "digital-logic-design-topic-14-dont-care-conditions",
            "title": "Don’t-care conditions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "digital-logic-design-topic-15-k-map-dont-care-conditions",
            "title": "K-map don’t-care conditions"
          }
        ],
        "assessments": [
          "Assignment #02"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "digital-logic-design-topic-16-nand-nor-and-exclusive-or-gates-and-circuits",
            "title": "NAND, NOR and Exclusive-OR Gates and Circuits"
          },
          {
            "id": "digital-logic-design-topic-17-integrated-circuits",
            "title": "Integrated Circuits"
          },
          {
            "id": "digital-logic-design-topic-18-positive-and-negative-logic",
            "title": "Positive and Negative Logic"
          }
        ],
        "assessments": [
          "Quiz #02"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-milestone-9",
        "type": "milestone",
        "title": "Mid-Semester Examination",
        "label": null
      },
      {
        "id": "digital-logic-design-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [
          {
            "id": "digital-logic-design-topic-19-combinational-circuits",
            "title": "Combinational Circuits"
          },
          {
            "id": "digital-logic-design-topic-20-analysis-procedure",
            "title": "Analysis Procedure"
          },
          {
            "id": "digital-logic-design-topic-21-design-procedure",
            "title": "Design Procedure"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "digital-logic-design-topic-22-decoders",
            "title": "Decoders"
          },
          {
            "id": "digital-logic-design-topic-23-encoders",
            "title": "Encoders"
          },
          {
            "id": "digital-logic-design-topic-24-priority-encoders",
            "title": "Priority Encoders"
          }
        ],
        "assessments": [
          "Assignment #03"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "digital-logic-design-topic-25-multiplexers",
            "title": "Multiplexers"
          },
          {
            "id": "digital-logic-design-topic-26-demultiplexers",
            "title": "Demultiplexers"
          },
          {
            "id": "digital-logic-design-topic-27-binary-adders",
            "title": "Binary Adders",
            "children": [
              {
                "id": "digital-logic-design-topic-28-half-adder",
                "title": "Half Adder"
              },
              {
                "id": "digital-logic-design-topic-29-full-adder",
                "title": "Full Adder"
              },
              {
                "id": "digital-logic-design-topic-30-ripple-carry",
                "title": "Ripple Carry"
              },
              {
                "id": "digital-logic-design-topic-31-carry-lookahead",
                "title": "Carry Lookahead"
              }
            ]
          }
        ],
        "assessments": [
          "Quiz #03"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "digital-logic-design-topic-32-binary-subtraction",
            "title": "Binary Subtraction"
          },
          {
            "id": "digital-logic-design-topic-33-signed-binary-numbers",
            "title": "Signed Binary Numbers"
          },
          {
            "id": "digital-logic-design-topic-34-overflow",
            "title": "Overflow"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "digital-logic-design-topic-35-sequential-circuits",
            "title": "Sequential Circuits"
          },
          {
            "id": "digital-logic-design-topic-36-latches",
            "title": "Latches"
          },
          {
            "id": "digital-logic-design-topic-37-flip-flops",
            "title": "Flip-Flops"
          },
          {
            "id": "digital-logic-design-topic-38-sequential-circuit-analysis",
            "title": "Sequential Circuit Analysis"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "digital-logic-design-topic-39-state-diagram",
            "title": "State Diagram"
          },
          {
            "id": "digital-logic-design-topic-40-sequential-circuit-design-word-problems",
            "title": "Sequential Circuit Design Word Problems"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "digital-logic-design-topic-41-registers-and-counters",
            "title": "Registers and Counters"
          },
          {
            "id": "digital-logic-design-topic-42-register-with-parallel-load",
            "title": "Register with Parallel Load"
          },
          {
            "id": "digital-logic-design-topic-43-shift-registers",
            "title": "Shift Registers"
          },
          {
            "id": "digital-logic-design-topic-44-shift-register-with-parallel-load",
            "title": "Shift Register with Parallel Load"
          },
          {
            "id": "digital-logic-design-topic-45-serial-and-parallel-counters",
            "title": "Serial and Parallel Counters"
          },
          {
            "id": "digital-logic-design-topic-46-up-down-binary-counter",
            "title": "Up-Down Binary Counter"
          },
          {
            "id": "digital-logic-design-topic-47-binary-counter-with-parallel-load",
            "title": "Binary Counter with Parallel Load"
          }
        ],
        "assessments": [
          "Assignment #04"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "digital-logic-design-topic-48-programmable-logic-technologies",
            "title": "Programmable Logic Technologies"
          },
          {
            "id": "digital-logic-design-topic-49-read-only-memory",
            "title": "Read-only Memory"
          },
          {
            "id": "digital-logic-design-topic-50-programmable-logic-arrays",
            "title": "Programmable Logic Arrays"
          },
          {
            "id": "digital-logic-design-topic-51-programmable-array-logic-devices",
            "title": "Programmable Array Logic Devices"
          },
          {
            "id": "digital-logic-design-topic-52-introduction-to-fpgas",
            "title": "Introduction to FPGAs"
          }
        ],
        "assessments": [
          "Quiz #04"
        ],
        "milestones": []
      },
      {
        "id": "digital-logic-design-milestone-18",
        "type": "milestone",
        "title": "Final Semester Examination",
        "label": null
      }
    ],
    "topicCount": 52,
    "curriculumVersion": "5a26ddcfbd332cfd34f20af08422f69505fb469380c56ea70b1970aa49266d6d"
  },
  "discrete-mathematics": {
    "subjectSlug": "discrete-mathematics",
    "units": [
      {
        "id": "discrete-mathematics-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "discrete-mathematics-topic-1-sets-introduction-to-sets",
            "title": "Sets: Introduction to sets"
          },
          {
            "id": "discrete-mathematics-topic-2-set-operations",
            "title": "Set operations"
          },
          {
            "id": "discrete-mathematics-topic-3-union",
            "title": "Union"
          },
          {
            "id": "discrete-mathematics-topic-4-intersection",
            "title": "Intersection"
          },
          {
            "id": "discrete-mathematics-topic-5-difference",
            "title": "Difference"
          },
          {
            "id": "discrete-mathematics-topic-6-absolute-difference",
            "title": "Absolute difference"
          },
          {
            "id": "discrete-mathematics-topic-7-relative-difference",
            "title": "Relative difference"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "discrete-mathematics-topic-8-functions",
            "title": "Functions"
          },
          {
            "id": "discrete-mathematics-topic-9-introduction-to-functions",
            "title": "Introduction to functions"
          },
          {
            "id": "discrete-mathematics-topic-10-injective-function",
            "title": "Injective function"
          },
          {
            "id": "discrete-mathematics-topic-11-bijective-function",
            "title": "Bijective function"
          },
          {
            "id": "discrete-mathematics-topic-12-composition-of-functions",
            "title": "Composition of functions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "discrete-mathematics-topic-13-characteristic-functions-with-computer-applications",
            "title": "Characteristic functions with computer applications"
          }
        ],
        "assessments": [
          "Assignment #01"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "discrete-mathematics-topic-14-sequences",
            "title": "Sequences"
          },
          {
            "id": "discrete-mathematics-topic-15-types-of-sequences",
            "title": "Types of sequences"
          },
          {
            "id": "discrete-mathematics-topic-16-convergence-of-sequences",
            "title": "Convergence of sequences"
          },
          {
            "id": "discrete-mathematics-topic-17-series",
            "title": "Series"
          },
          {
            "id": "discrete-mathematics-topic-18-types-of-series",
            "title": "Types of series"
          },
          {
            "id": "discrete-mathematics-topic-19-convergence-of-series",
            "title": "Convergence of series"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "discrete-mathematics-topic-20-relations",
            "title": "Relations"
          },
          {
            "id": "discrete-mathematics-topic-21-introduction-to-relations",
            "title": "Introduction to relations"
          },
          {
            "id": "discrete-mathematics-topic-22-binary-relations",
            "title": "Binary relations"
          },
          {
            "id": "discrete-mathematics-topic-23-n-array-relations",
            "title": "n-array relations"
          },
          {
            "id": "discrete-mathematics-topic-24-congruence-relations",
            "title": "Congruence relations"
          },
          {
            "id": "discrete-mathematics-topic-25-representation-of-relation",
            "title": "Representation of relation"
          },
          {
            "id": "discrete-mathematics-topic-26-partitions",
            "title": "Partitions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "discrete-mathematics-topic-27-equivalence-relations",
            "title": "Equivalence Relations"
          },
          {
            "id": "discrete-mathematics-topic-28-equivalence-class",
            "title": "Equivalence Class"
          },
          {
            "id": "discrete-mathematics-topic-29-partial-ordering",
            "title": "Partial ordering"
          }
        ],
        "assessments": [
          "Quiz #01"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "discrete-mathematics-topic-30-properties-of-general-relations",
            "title": "Properties of General Relations"
          },
          {
            "id": "discrete-mathematics-topic-31-introduction-to-combinatorics",
            "title": "Introduction to combinatorics"
          },
          {
            "id": "discrete-mathematics-topic-32-basic-counting-techniques",
            "title": "Basic counting techniques"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "discrete-mathematics-topic-33-covering-of-sets",
            "title": "Covering of sets"
          },
          {
            "id": "discrete-mathematics-topic-34-posets",
            "title": "Posets"
          },
          {
            "id": "discrete-mathematics-topic-35-hasse-diagrams-with-applications",
            "title": "Hasse diagrams with applications"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Mid-Semester Examination"
        ]
      },
      {
        "id": "discrete-mathematics-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "discrete-mathematics-topic-36-the-logic-of-compound-statements",
            "title": "The logic of compound statements"
          },
          {
            "id": "discrete-mathematics-topic-37-logical-equivalence",
            "title": "Logical equivalence"
          },
          {
            "id": "discrete-mathematics-topic-38-conditional-statements",
            "title": "Conditional statements"
          },
          {
            "id": "discrete-mathematics-topic-39-valid-and-invalid-argument",
            "title": "Valid and invalid argument"
          },
          {
            "id": "discrete-mathematics-topic-40-biconditional-statements",
            "title": "Biconditional statements"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "discrete-mathematics-topic-41-properties-of-logical-equivalence-with-computer-applications",
            "title": "Properties of logical equivalence with computer applications"
          },
          {
            "id": "discrete-mathematics-topic-42-quantifiers",
            "title": "Quantifiers"
          },
          {
            "id": "discrete-mathematics-topic-43-proof-techniques",
            "title": "Proof techniques"
          },
          {
            "id": "discrete-mathematics-topic-44-language-of-proofs",
            "title": "Language of proofs"
          }
        ],
        "assessments": [
          "Assignment #02"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "discrete-mathematics-topic-45-applications",
            "title": "Applications"
          },
          {
            "id": "discrete-mathematics-topic-46-digital-logic-circuits",
            "title": "Digital logic circuits"
          },
          {
            "id": "discrete-mathematics-topic-47-different-types-of-logic-gates",
            "title": "Different types of logic gates"
          },
          {
            "id": "discrete-mathematics-topic-48-boolean-expressions",
            "title": "Boolean expressions"
          },
          {
            "id": "discrete-mathematics-topic-49-simplification-of-circuits",
            "title": "Simplification of circuits"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "discrete-mathematics-topic-50-partitioning-properties-with-computer-applications",
            "title": "Partitioning properties with computer applications"
          }
        ],
        "assessments": [
          "Quiz #02"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "discrete-mathematics-topic-51-counting",
            "title": "Counting"
          },
          {
            "id": "discrete-mathematics-topic-52-addition-rule",
            "title": "Addition rule"
          },
          {
            "id": "discrete-mathematics-topic-53-multiplication-rule",
            "title": "Multiplication rule"
          },
          {
            "id": "discrete-mathematics-topic-54-permutations-and-combinations",
            "title": "Permutations and combinations"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "discrete-mathematics-topic-55-counting-with-repetitions",
            "title": "Counting with repetitions"
          },
          {
            "id": "discrete-mathematics-topic-56-combinatorial-identities",
            "title": "Combinatorial identities"
          },
          {
            "id": "discrete-mathematics-topic-57-pigeon-hole-principle",
            "title": "Pigeon hole principle"
          },
          {
            "id": "discrete-mathematics-topic-58-inclusion-exclusion-principle",
            "title": "Inclusion-exclusion principle"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "discrete-mathematics-topic-59-graphs",
            "title": "Graphs"
          },
          {
            "id": "discrete-mathematics-topic-60-introduction-to-graphs",
            "title": "Introduction to graphs"
          },
          {
            "id": "discrete-mathematics-topic-61-graph-terminology",
            "title": "Graph terminology"
          },
          {
            "id": "discrete-mathematics-topic-62-connectivity-in-graphs",
            "title": "Connectivity in graphs"
          },
          {
            "id": "discrete-mathematics-topic-63-euler-and-hamilton-paths",
            "title": "Euler and Hamilton paths"
          },
          {
            "id": "discrete-mathematics-topic-64-shortest-path-problems",
            "title": "Shortest path problems"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-17",
        "type": "week",
        "title": "Week 17",
        "topics": [
          {
            "id": "discrete-mathematics-topic-65-trees-sorting",
            "title": "Trees & Sorting"
          },
          {
            "id": "discrete-mathematics-topic-66-introduction-to-trees",
            "title": "Introduction to trees"
          },
          {
            "id": "discrete-mathematics-topic-67-application-of-trees",
            "title": "Application of trees"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "discrete-mathematics-week-18",
        "type": "week",
        "title": "Week 18",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Final Semester Examination"
        ]
      }
    ],
    "topicCount": 67,
    "curriculumVersion": "25f9c6ec415c660b13dd60c4ecce8b25e1de333c7307d66cc20706762eb059b6"
  },
  "expository-writing": {
    "subjectSlug": "expository-writing",
    "units": [
      {
        "id": "expository-writing-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "expository-writing-topic-1-writing-process",
            "title": "Writing Process"
          },
          {
            "id": "expository-writing-topic-2-purpose-and-audience",
            "title": "Purpose and Audience"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "expository-writing-topic-3-paragraph-writing",
            "title": "Paragraph Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "expository-writing-topic-4-essay-writing",
            "title": "Essay Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "expository-writing-topic-5-descriptive-essays",
            "title": "Descriptive Essays"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "expository-writing-topic-6-persuasive-writing",
            "title": "Persuasive Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "expository-writing-topic-7-sentence-errors",
            "title": "Sentence Errors"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "expository-writing-topic-8-how-to-give-presentations",
            "title": "How to Give Presentations"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "expository-writing-topic-9-oral-presentations",
            "title": "Oral Presentations"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-milestone-9",
        "type": "milestone",
        "title": "Mid Semester Exam",
        "label": null
      },
      {
        "id": "expository-writing-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [
          {
            "id": "expository-writing-topic-10-comparison-and-contrast-essays",
            "title": "Comparison and Contrast Essays"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "expository-writing-topic-11-dialogue-writing",
            "title": "Dialogue Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "expository-writing-topic-12-short-story-writing",
            "title": "Short Story Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "expository-writing-topic-13-review-writing",
            "title": "Review Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "expository-writing-topic-14-narrative-essays",
            "title": "Narrative Essays"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "expository-writing-topic-15-letter-writing",
            "title": "Letter Writing"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "expository-writing-topic-16-public-speaking",
            "title": "Public Speaking"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "expository-writing-milestone-17",
        "type": "milestone",
        "title": "End Semester Exam",
        "label": null
      }
    ],
    "topicCount": 16,
    "curriculumVersion": "23a6fbacb981f7bf1d4556177a8284a3fa8601104eccf2aa1786538dd379d291"
  },
  "ideology-constitution-pakistan": {
    "subjectSlug": "ideology-constitution-pakistan",
    "units": [
      {
        "id": "ideology-constitution-pakistan-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-1-ideology",
            "title": "Ideology"
          },
          {
            "id": "ideology-constitution-pakistan-topic-2-definition",
            "title": "Definition"
          },
          {
            "id": "ideology-constitution-pakistan-topic-3-explanation",
            "title": "Explanation"
          },
          {
            "id": "ideology-constitution-pakistan-topic-4-main-kinds-of-ideology",
            "title": "Main kinds of ideology"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-5-the-pakistan-ideology",
            "title": "The Pakistan Ideology"
          },
          {
            "id": "ideology-constitution-pakistan-topic-6-definition",
            "title": "Definition"
          },
          {
            "id": "ideology-constitution-pakistan-topic-7-aims-and-objectives",
            "title": "Aims and objectives"
          },
          {
            "id": "ideology-constitution-pakistan-topic-8-vision-of-quaid-e-azam-mohammad-ali-jinnah",
            "title": "Vision of Quaid-e-Azam Mohammad Ali Jinnah"
          },
          {
            "id": "ideology-constitution-pakistan-topic-9-vision-of-dr-allama-iqbal",
            "title": "Vision of Dr. Allama Iqbal"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-10-historical-background",
            "title": "Historical Background"
          },
          {
            "id": "ideology-constitution-pakistan-topic-11-hazrat-shah-wali-ullah",
            "title": "Hazrat Shah Wali Ullah"
          },
          {
            "id": "ideology-constitution-pakistan-topic-12-mujahideen-movement",
            "title": "Mujahideen Movement"
          },
          {
            "id": "ideology-constitution-pakistan-topic-13-war-of-independence-1857-and-its-impacts",
            "title": "War of Independence 1857 and its impacts"
          },
          {
            "id": "ideology-constitution-pakistan-topic-14-role-of-sir-sayed-ahmad-khan-after-1857-war",
            "title": "Role of Sir Sayed Ahmad Khan after 1857 war"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-15-educational-movements",
            "title": "Educational Movements"
          },
          {
            "id": "ideology-constitution-pakistan-topic-16-aligarh-school-of-thought",
            "title": "Aligarh School of Thought"
          },
          {
            "id": "ideology-constitution-pakistan-topic-17-deoband-school-of-thought",
            "title": "Deoband School of Thought"
          },
          {
            "id": "ideology-constitution-pakistan-topic-18-nadwa-tul-ulema",
            "title": "Nadwa-tul-Ulema"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-19-establishment-of-indian-national-congress",
            "title": "Establishment of Indian National Congress"
          },
          {
            "id": "ideology-constitution-pakistan-topic-20-evolution-of-two-nation-theory",
            "title": "Evolution of Two Nation Theory"
          },
          {
            "id": "ideology-constitution-pakistan-topic-21-partition-of-bengal-1905",
            "title": "Partition of Bengal 1905"
          },
          {
            "id": "ideology-constitution-pakistan-topic-22-simla-deputation-1906",
            "title": "Simla Deputation 1906"
          },
          {
            "id": "ideology-constitution-pakistan-topic-23-establishment-of-muslim-league-1906",
            "title": "Establishment of Muslim League 1906"
          },
          {
            "id": "ideology-constitution-pakistan-topic-24-lahore-resolution-1940",
            "title": "Lahore Resolution 1940"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-25-early-constitutions-in-the-world",
            "title": "Early Constitutions in the world"
          },
          {
            "id": "ideology-constitution-pakistan-topic-26-charter-of-medina",
            "title": "Charter of Medina"
          },
          {
            "id": "ideology-constitution-pakistan-topic-27-magna-carta",
            "title": "Magna Carta"
          },
          {
            "id": "ideology-constitution-pakistan-topic-28-concept-of-constitutional-government",
            "title": "Concept of constitutional government"
          },
          {
            "id": "ideology-constitution-pakistan-topic-29-evolution-of-constitutionalism",
            "title": "Evolution of constitutionalism"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-30-constitutional-and-political-reforms-in-british-india-1858-1892",
            "title": "Constitutional and Political Reforms in British India 1858–1892"
          },
          {
            "id": "ideology-constitution-pakistan-topic-31-minto-morley-reforms-1909",
            "title": "Minto-Morley Reforms (1909)"
          },
          {
            "id": "ideology-constitution-pakistan-topic-32-montagu-chelmsford-reforms-1919",
            "title": "Montagu-Chelmsford Reforms (1919)"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-33-government-of-india-act-of-1935",
            "title": "Government of India Act of 1935"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Mid Semester Exam"
        ]
      },
      {
        "id": "ideology-constitution-pakistan-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-34-background-and-main-provision-of-indian-independence-act-1947",
            "title": "Background and Main Provision of Indian Independence Act 1947"
          },
          {
            "id": "ideology-constitution-pakistan-topic-35-implementation",
            "title": "Implementation"
          },
          {
            "id": "ideology-constitution-pakistan-topic-36-consequences",
            "title": "Consequences"
          },
          {
            "id": "ideology-constitution-pakistan-topic-37-historical-significance",
            "title": "Historical Significance"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-38-political-and-constitutional-development-in-pakistan-1947-56",
            "title": "Political and Constitutional development in Pakistan 1947–56"
          },
          {
            "id": "ideology-constitution-pakistan-topic-39-objective-resolution-1949",
            "title": "Objective Resolution 1949"
          },
          {
            "id": "ideology-constitution-pakistan-topic-40-role-of-constituent-assembly",
            "title": "Role of Constituent Assembly"
          },
          {
            "id": "ideology-constitution-pakistan-topic-41-first-report-of-basic-principle-committee",
            "title": "First Report of Basic Principle Committee"
          },
          {
            "id": "ideology-constitution-pakistan-topic-42-second-report-of-basic-principle-committee",
            "title": "Second Report of Basic Principle Committee"
          },
          {
            "id": "ideology-constitution-pakistan-topic-43-constitutional-deadlock-for-nine-years",
            "title": "Constitutional deadlock for nine years"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-44-constitution-of-1956",
            "title": "Constitution of 1956"
          },
          {
            "id": "ideology-constitution-pakistan-topic-45-salient-features",
            "title": "Salient features"
          },
          {
            "id": "ideology-constitution-pakistan-topic-46-shortcomings-of-1956-constitution",
            "title": "Shortcomings of 1956 Constitution"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-47-ayub-khan-martial-law-1958",
            "title": "Ayub Khan Martial law 1958"
          },
          {
            "id": "ideology-constitution-pakistan-topic-48-background-and-constitution-of-1962",
            "title": "Background and Constitution of 1962"
          },
          {
            "id": "ideology-constitution-pakistan-topic-49-features-of-constitution-of-1962",
            "title": "Features of Constitution of 1962"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-50-constitution-of-pakistan-1973",
            "title": "Constitution of Pakistan 1973"
          },
          {
            "id": "ideology-constitution-pakistan-topic-51-salient-features",
            "title": "Salient features"
          },
          {
            "id": "ideology-constitution-pakistan-topic-52-significance-of-1973-constitution",
            "title": "Significance of 1973 Constitution"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-53-political-developments-in-general-zia-ul-haqs-era",
            "title": "Political Developments in General Zia Ul Haq’s Era"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-54-constitutional-amendments-of-1973-constitution",
            "title": "Constitutional Amendments of 1973 Constitution:",
            "children": [
              {
                "id": "ideology-constitution-pakistan-topic-55-8th",
                "title": "8th"
              },
              {
                "id": "ideology-constitution-pakistan-topic-56-13th",
                "title": "13th"
              },
              {
                "id": "ideology-constitution-pakistan-topic-57-17th",
                "title": "17th"
              },
              {
                "id": "ideology-constitution-pakistan-topic-58-18th",
                "title": "18th"
              }
            ]
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-17",
        "type": "week",
        "title": "Week 17",
        "topics": [
          {
            "id": "ideology-constitution-pakistan-topic-59-constitutional-amendments-of-1973-constitution",
            "title": "Constitutional Amendments of 1973 Constitution:",
            "children": [
              {
                "id": "ideology-constitution-pakistan-topic-60-19th",
                "title": "19th"
              },
              {
                "id": "ideology-constitution-pakistan-topic-61-21st",
                "title": "21st"
              },
              {
                "id": "ideology-constitution-pakistan-topic-62-25th",
                "title": "25th"
              }
            ]
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "ideology-constitution-pakistan-week-18",
        "type": "week",
        "title": "Week 18",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Final Term Examination"
        ]
      }
    ],
    "topicCount": 62,
    "curriculumVersion": "96709c4e30207d8fab627dfd22a1ad84ae164cf9fb72372e5307c77c3d605b36"
  },
  "mathematics-2": {
    "subjectSlug": "mathematics-2",
    "units": [
      {
        "id": "mathematics-2-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "mathematics-2-topic-1-concept-of-function",
            "title": "Concept of function"
          },
          {
            "id": "mathematics-2-topic-2-domain-and-range-of-a-function",
            "title": "Domain and range of a function"
          },
          {
            "id": "mathematics-2-topic-3-notation-and-value-of-a-function",
            "title": "Notation and value of a function"
          },
          {
            "id": "mathematics-2-topic-4-types-of-functions",
            "title": "Types of functions"
          },
          {
            "id": "mathematics-2-topic-5-graph-sketching",
            "title": "Graph sketching"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "mathematics-2-topic-6-limits-of-a-function",
            "title": "Limits of a function"
          },
          {
            "id": "mathematics-2-topic-7-theorems-on-limits",
            "title": "Theorems on limits"
          },
          {
            "id": "mathematics-2-topic-8-left-and-right-hand-limits",
            "title": "Left- and right-hand limits"
          },
          {
            "id": "mathematics-2-topic-9-limits-at-infinity",
            "title": "Limits at infinity"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "mathematics-2-topic-10-continuous-and-discontinuous-functions",
            "title": "Continuous and discontinuous functions"
          },
          {
            "id": "mathematics-2-topic-11-criteria-for-existence-of-a-limit-of-function",
            "title": "Criteria for existence of a limit of function"
          },
          {
            "id": "mathematics-2-topic-12-continuity-of-a-function-at-a-point",
            "title": "Continuity of a function at a point"
          },
          {
            "id": "mathematics-2-topic-13-continuity-at-entire-domain",
            "title": "Continuity at entire domain"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "mathematics-2-topic-14-dependent-and-independent-variables",
            "title": "Dependent and independent variables"
          },
          {
            "id": "mathematics-2-topic-15-average-rate-of-change",
            "title": "Average rate of change"
          },
          {
            "id": "mathematics-2-topic-16-derivative-of-a-function",
            "title": "Derivative of a function"
          },
          {
            "id": "mathematics-2-topic-17-notation-for-derivative",
            "title": "Notation for derivative"
          },
          {
            "id": "mathematics-2-topic-18-derivative-as-limit-of-a-function",
            "title": "Derivative as limit of a function"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "mathematics-2-topic-19-theorems-on-derivative",
            "title": "Theorems on derivative"
          },
          {
            "id": "mathematics-2-topic-20-chain-rule-of-derivative",
            "title": "Chain Rule of derivative"
          },
          {
            "id": "mathematics-2-topic-21-derivative-of-inverse-functions",
            "title": "Derivative of inverse functions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "mathematics-2-topic-22-derivative-of-polynomial-functions",
            "title": "Derivative of polynomial functions"
          },
          {
            "id": "mathematics-2-topic-23-derivative-of-parametric-functions",
            "title": "Derivative of parametric functions"
          },
          {
            "id": "mathematics-2-topic-24-derivative-of-implicit-relations",
            "title": "Derivative of implicit relations"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "mathematics-2-topic-25-derivative-of-trigonometric-and-inverse-trigonometric-functions",
            "title": "Derivative of trigonometric and inverse trigonometric functions"
          },
          {
            "id": "mathematics-2-topic-26-derivative-of-exponential-functions",
            "title": "Derivative of exponential functions"
          },
          {
            "id": "mathematics-2-topic-27-logarithmic-functions",
            "title": "Logarithmic functions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "mathematics-2-topic-28-derivative-of-hyperbolic-functions-and-inverse-hyperbolic-functions",
            "title": "Derivative of hyperbolic functions and inverse hyperbolic functions"
          },
          {
            "id": "mathematics-2-topic-29-higher-order-derivatives",
            "title": "Higher order derivatives"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [
          {
            "id": "mathematics-2-topic-30-series-expansions-of-functions",
            "title": "Series expansions of functions"
          },
          {
            "id": "mathematics-2-topic-31-maclaurin-theorem",
            "title": "Maclaurin theorem"
          },
          {
            "id": "mathematics-2-topic-32-taylors-series-expansion-of-functions",
            "title": "Taylor’s series expansion of functions"
          },
          {
            "id": "mathematics-2-topic-33-geometrical-interpretation-of-derivative",
            "title": "Geometrical interpretation of derivative"
          },
          {
            "id": "mathematics-2-topic-34-increasing-and-decreasing-functions",
            "title": "Increasing and decreasing functions"
          },
          {
            "id": "mathematics-2-topic-35-maxima-and-minima",
            "title": "Maxima and minima"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "mathematics-2-topic-36-integration-as-anti-derivative",
            "title": "Integration as anti-derivative"
          },
          {
            "id": "mathematics-2-topic-37-theorems-on-anti-derivative",
            "title": "Theorems on anti-derivative"
          },
          {
            "id": "mathematics-2-topic-38-integration-by-substitution-method",
            "title": "Integration by substitution method"
          },
          {
            "id": "mathematics-2-topic-39-by-parts-method-of-integration",
            "title": "By parts method of integration"
          },
          {
            "id": "mathematics-2-topic-40-integration-of-partial-fractions",
            "title": "Integration of partial fractions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "mathematics-2-topic-41-definition-of-differential-equation",
            "title": "Definition of Differential equation"
          },
          {
            "id": "mathematics-2-topic-42-order-and-degree-of-differential-equation",
            "title": "Order and degree of differential equation"
          },
          {
            "id": "mathematics-2-topic-43-solution-of-1st-order-differential-equation",
            "title": "Solution of 1st order differential equation"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "mathematics-2-topic-44-introduction-to-analytical-geometry",
            "title": "Introduction to analytical geometry"
          },
          {
            "id": "mathematics-2-topic-45-types-of-straight-lines",
            "title": "Types of straight lines"
          },
          {
            "id": "mathematics-2-topic-46-translation-and-rotation-of-axes",
            "title": "Translation and rotation of axes"
          },
          {
            "id": "mathematics-2-topic-47-general-equation-of-2nd-degree",
            "title": "General equation of 2nd degree"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "mathematics-2-topic-48-line-through-the-intersection-of-two-lines",
            "title": "Line through the intersection of two lines"
          },
          {
            "id": "mathematics-2-topic-49-distance-of-point-from-a-line",
            "title": "Distance of point from a line"
          },
          {
            "id": "mathematics-2-topic-50-area-of-triangular-region",
            "title": "Area of triangular region"
          },
          {
            "id": "mathematics-2-topic-51-angle-between-two-lines",
            "title": "Angle between two lines"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "mathematics-2-topic-52-linear-inequalities",
            "title": "Linear inequalities"
          },
          {
            "id": "mathematics-2-topic-53-graphing-of-linear-inequalities-in-two-variables",
            "title": "Graphing of linear inequalities in two variables"
          },
          {
            "id": "mathematics-2-topic-54-feasible-solution-set",
            "title": "Feasible solution set"
          },
          {
            "id": "mathematics-2-topic-55-linear-programming",
            "title": "Linear programming"
          },
          {
            "id": "mathematics-2-topic-56-linear-programming-problems",
            "title": "Linear programming problems"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "mathematics-2-topic-57-introduction-to-conic-sections",
            "title": "Introduction to conic sections"
          },
          {
            "id": "mathematics-2-topic-58-equation-of-a-circle-in-different-forms",
            "title": "Equation of a circle in different forms"
          },
          {
            "id": "mathematics-2-topic-59-tangent-and-normal",
            "title": "Tangent and normal"
          },
          {
            "id": "mathematics-2-topic-60-equation-of-parabola-ellipse-and-hyperbola",
            "title": "Equation of parabola, ellipse, and hyperbola"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "mathematics-2-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "mathematics-2-topic-61-introduction-to-scalars-and-vectors",
            "title": "Introduction to scalars and vectors"
          },
          {
            "id": "mathematics-2-topic-62-algebra-of-vectors",
            "title": "Algebra of vectors"
          },
          {
            "id": "mathematics-2-topic-63-properties-of-vectors",
            "title": "Properties of vectors"
          },
          {
            "id": "mathematics-2-topic-64-dot-and-cross-product-of-vectors",
            "title": "Dot and cross product of vectors"
          }
        ],
        "assessments": [],
        "milestones": []
      }
    ],
    "topicCount": 64,
    "curriculumVersion": "c80027482d349e9e8c5dc1e24fcb239e5b53e49a8193ca449de5327fdeaff283"
  },
  "oop": {
    "subjectSlug": "oop",
    "units": [
      {
        "id": "oop-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "oop-topic-1-problem-solving-in-object-oriented-programming",
            "title": "Problem solving in Object oriented Programming"
          },
          {
            "id": "oop-topic-2-revision-of-structures",
            "title": "Revision of Structures"
          },
          {
            "id": "oop-topic-3-identification-of-problems-in-structural-programming",
            "title": "Identification of problems in structural programming"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "oop-topic-4-structures-vs-classes",
            "title": "Structures vs classes"
          },
          {
            "id": "oop-topic-5-classes-and-objects",
            "title": "Classes and objects"
          },
          {
            "id": "oop-topic-6-basics-of-classes-and-objects",
            "title": "Basics of classes and objects"
          },
          {
            "id": "oop-topic-7-syntax-of-class",
            "title": "Syntax of class"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "oop-topic-8-data-members",
            "title": "Data Members"
          },
          {
            "id": "oop-topic-9-data-encapsulation",
            "title": "Data encapsulation"
          },
          {
            "id": "oop-topic-10-member-access-specifiers",
            "title": "Member Access specifiers"
          },
          {
            "id": "oop-topic-11-types-of-data-members",
            "title": "Types of data members"
          },
          {
            "id": "oop-topic-12-accessing-data-from-objects",
            "title": "Accessing data from objects"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "oop-topic-13-member-functions",
            "title": "Member functions"
          },
          {
            "id": "oop-topic-14-constructors-and-destructors",
            "title": "Constructors and destructors"
          }
        ],
        "assessments": [
          "Assignment #01"
        ],
        "milestones": []
      },
      {
        "id": "oop-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "oop-topic-15-function-overloading",
            "title": "Function overloading"
          }
        ],
        "assessments": [
          "Quiz #01"
        ],
        "milestones": []
      },
      {
        "id": "oop-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "oop-topic-16-constructor-overloading",
            "title": "Constructor overloading"
          },
          {
            "id": "oop-topic-17-default-constructor",
            "title": "Default constructor"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "oop-topic-18-operator-overloading",
            "title": "Operator overloading"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "oop-topic-19-overloading-unary-and-binary-operators",
            "title": "Overloading unary and binary operators"
          }
        ],
        "assessments": [
          "Assignment #02"
        ],
        "milestones": []
      },
      {
        "id": "oop-milestone-9",
        "type": "milestone",
        "title": "Mid Term",
        "label": null
      },
      {
        "id": "oop-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [
          {
            "id": "oop-topic-20-inheritance",
            "title": "Inheritance"
          },
          {
            "id": "oop-topic-21-basics-of-inheritance",
            "title": "Basics of inheritance"
          },
          {
            "id": "oop-topic-22-base-class",
            "title": "Base class"
          },
          {
            "id": "oop-topic-23-child-class",
            "title": "Child class"
          }
        ],
        "assessments": [
          "Quiz #02"
        ],
        "milestones": []
      },
      {
        "id": "oop-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "oop-topic-24-types-of-inheritance",
            "title": "Types of inheritance"
          },
          {
            "id": "oop-topic-25-rules-for-public-private-protected-inheritance",
            "title": "Rules for Public, Private, Protected inheritance"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "oop-topic-26-function-overriding",
            "title": "Function overriding"
          },
          {
            "id": "oop-topic-27-multiple-inheritance",
            "title": "Multiple inheritance"
          },
          {
            "id": "oop-topic-28-polymorphism",
            "title": "Polymorphism"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "oop-topic-29-virtual-functions",
            "title": "Virtual functions"
          },
          {
            "id": "oop-topic-30-friend-functions",
            "title": "Friend functions"
          },
          {
            "id": "oop-topic-31-static-functions",
            "title": "Static functions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "oop-topic-32-relationship-between-classes",
            "title": "Relationship between classes:",
            "children": [
              {
                "id": "oop-topic-33-association",
                "title": "Association"
              },
              {
                "id": "oop-topic-34-aggregation",
                "title": "Aggregation"
              },
              {
                "id": "oop-topic-35-composition",
                "title": "Composition"
              },
              {
                "id": "oop-topic-36-generalization",
                "title": "Generalization"
              },
              {
                "id": "oop-topic-37-inner-nested-classes",
                "title": "Inner/nested classes"
              }
            ]
          }
        ],
        "assessments": [
          "Assignment #03"
        ],
        "milestones": []
      },
      {
        "id": "oop-weeks-14-15",
        "type": "week",
        "title": "Weeks 14–15",
        "topics": [
          {
            "id": "oop-topic-38-exceptions",
            "title": "Exceptions"
          },
          {
            "id": "oop-topic-39-exception-handling",
            "title": "Exception Handling"
          },
          {
            "id": "oop-topic-40-stream-classes",
            "title": "Stream Classes"
          },
          {
            "id": "oop-topic-41-stream-errors",
            "title": "Stream errors"
          },
          {
            "id": "oop-topic-42-file-handling",
            "title": "File handling"
          },
          {
            "id": "oop-topic-43-fundamentals-of-pointers",
            "title": "Fundamentals of pointers"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "oop-topic-44-templates",
            "title": "Templates"
          },
          {
            "id": "oop-topic-45-function-templates",
            "title": "Function templates"
          },
          {
            "id": "oop-topic-46-class-templates",
            "title": "Class templates"
          },
          {
            "id": "oop-topic-47-standard-template-library",
            "title": "Standard Template Library"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "oop-milestone-17",
        "type": "milestone",
        "title": "End Semester Exam",
        "label": null
      },
      {
        "id": "oop-week-18",
        "type": "week",
        "title": "Week 18",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Final Semester Examination"
        ]
      }
    ],
    "topicCount": 47,
    "curriculumVersion": "a21e751bf5a48048af0eed3ce911cf658bc47b739f2fc046834d2a0433ce26fb"
  },
  "probability-and-statistics": {
    "subjectSlug": "probability-and-statistics",
    "units": [
      {
        "id": "probability-and-statistics-week-1",
        "type": "week",
        "title": "Week 1",
        "topics": [
          {
            "id": "probability-and-statistics-topic-1-introduction-to-statistics-and-data-analysis",
            "title": "Introduction to Statistics and Data Analysis"
          },
          {
            "id": "probability-and-statistics-topic-2-statistical-inference",
            "title": "Statistical Inference"
          },
          {
            "id": "probability-and-statistics-topic-3-samples",
            "title": "Samples"
          },
          {
            "id": "probability-and-statistics-topic-4-populations",
            "title": "Populations"
          },
          {
            "id": "probability-and-statistics-topic-5-role-of-probability",
            "title": "Role of Probability"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-2",
        "type": "week",
        "title": "Week 2",
        "topics": [
          {
            "id": "probability-and-statistics-topic-6-sampling-procedures",
            "title": "Sampling Procedures"
          },
          {
            "id": "probability-and-statistics-topic-7-discrete-and-continuous-data",
            "title": "Discrete and Continuous Data"
          },
          {
            "id": "probability-and-statistics-topic-8-statistical-modeling",
            "title": "Statistical Modeling"
          },
          {
            "id": "probability-and-statistics-topic-9-types-of-statistical-studies",
            "title": "Types of Statistical Studies"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-3",
        "type": "week",
        "title": "Week 3",
        "topics": [
          {
            "id": "probability-and-statistics-topic-10-probability",
            "title": "Probability"
          },
          {
            "id": "probability-and-statistics-topic-11-sample-space",
            "title": "Sample Space"
          },
          {
            "id": "probability-and-statistics-topic-12-events",
            "title": "Events"
          },
          {
            "id": "probability-and-statistics-topic-13-counting-sample-points",
            "title": "Counting Sample Points"
          },
          {
            "id": "probability-and-statistics-topic-14-probability-of-an-event",
            "title": "Probability of an Event"
          },
          {
            "id": "probability-and-statistics-topic-15-additive-rules",
            "title": "Additive Rules"
          },
          {
            "id": "probability-and-statistics-topic-16-conditional-probability",
            "title": "Conditional Probability"
          },
          {
            "id": "probability-and-statistics-topic-17-independence",
            "title": "Independence"
          },
          {
            "id": "probability-and-statistics-topic-18-product-rule",
            "title": "Product Rule"
          },
          {
            "id": "probability-and-statistics-topic-19-bayes-rule",
            "title": "Bayes’ Rule"
          },
          {
            "id": "probability-and-statistics-topic-20-random-variables-and-probability-distributions",
            "title": "Random Variables and Probability Distributions"
          }
        ],
        "assessments": [
          "Assignment #01"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-4",
        "type": "week",
        "title": "Week 4",
        "topics": [
          {
            "id": "probability-and-statistics-topic-21-mathematical-expectation",
            "title": "Mathematical Expectation"
          },
          {
            "id": "probability-and-statistics-topic-22-mean-of-a-random-variable",
            "title": "Mean of a Random Variable"
          },
          {
            "id": "probability-and-statistics-topic-23-variance-and-covariance-of-random-variables",
            "title": "Variance and Covariance of Random Variables"
          },
          {
            "id": "probability-and-statistics-topic-24-means-and-variances-of-linear-combinations-of-random-variables",
            "title": "Means and Variances of Linear Combinations of Random Variables"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-5",
        "type": "week",
        "title": "Week 5",
        "topics": [
          {
            "id": "probability-and-statistics-topic-25-chebyshevs-theorem",
            "title": "Chebyshev’s Theorem"
          },
          {
            "id": "probability-and-statistics-topic-26-discrete-probability-distributions",
            "title": "Discrete Probability Distributions"
          },
          {
            "id": "probability-and-statistics-topic-27-continuous-probability-distributions",
            "title": "Continuous Probability Distributions"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-6",
        "type": "week",
        "title": "Week 6",
        "topics": [
          {
            "id": "probability-and-statistics-topic-28-fundamental-sampling-distributions-and-data-descriptions",
            "title": "Fundamental Sampling Distributions and Data Descriptions"
          },
          {
            "id": "probability-and-statistics-topic-29-random-sampling",
            "title": "Random Sampling"
          },
          {
            "id": "probability-and-statistics-topic-30-sampling-distributions",
            "title": "Sampling Distributions"
          }
        ],
        "assessments": [
          "Quiz #01"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-7",
        "type": "week",
        "title": "Week 7",
        "topics": [
          {
            "id": "probability-and-statistics-topic-31-sampling-distribution-of-means",
            "title": "Sampling Distribution of Means"
          },
          {
            "id": "probability-and-statistics-topic-32-central-limit-theorem",
            "title": "Central Limit Theorem"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-8",
        "type": "week",
        "title": "Week 8",
        "topics": [
          {
            "id": "probability-and-statistics-topic-33-sampling-distribution-of-s2",
            "title": "Sampling Distribution of S²"
          },
          {
            "id": "probability-and-statistics-topic-34-t-distribution",
            "title": "t-Distribution"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-9",
        "type": "week",
        "title": "Week 9",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Mid-Semester Examination"
        ]
      },
      {
        "id": "probability-and-statistics-week-10",
        "type": "week",
        "title": "Week 10",
        "topics": [
          {
            "id": "probability-and-statistics-topic-35-f-quantile-and-probability-plots",
            "title": "F Quantile and Probability Plots"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-11",
        "type": "week",
        "title": "Week 11",
        "topics": [
          {
            "id": "probability-and-statistics-topic-36-single-sample-estimation-problems",
            "title": "Single Sample Estimation Problems"
          },
          {
            "id": "probability-and-statistics-topic-37-one-and-two-sample-estimation-problems",
            "title": "One- and Two-Sample Estimation Problems"
          }
        ],
        "assessments": [
          "Assignment #02"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-12",
        "type": "week",
        "title": "Week 12",
        "topics": [
          {
            "id": "probability-and-statistics-topic-38-single-sample-tests-of-hypotheses",
            "title": "Single Sample Tests of Hypotheses"
          },
          {
            "id": "probability-and-statistics-topic-39-one-and-two-sample-tests-of-hypotheses",
            "title": "One- and Two-Sample Tests of Hypotheses"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-13",
        "type": "week",
        "title": "Week 13",
        "topics": [
          {
            "id": "probability-and-statistics-topic-40-use-of-p-values-for-decision-making-in-testing-hypotheses",
            "title": "Use of P-Values for Decision Making in Testing Hypotheses"
          },
          {
            "id": "probability-and-statistics-topic-41-single-sample-and-one-two-sample-tests",
            "title": "Single Sample and One-/Two-Sample Tests"
          }
        ],
        "assessments": [
          "Quiz #02"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-14",
        "type": "week",
        "title": "Week 14",
        "topics": [
          {
            "id": "probability-and-statistics-topic-42-linear-regression-and-correlation",
            "title": "Linear Regression and Correlation"
          }
        ],
        "assessments": [
          "Presentations"
        ],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-15",
        "type": "week",
        "title": "Week 15",
        "topics": [
          {
            "id": "probability-and-statistics-topic-43-least-squares-and-the-fitted-model",
            "title": "Least Squares and the Fitted Model"
          },
          {
            "id": "probability-and-statistics-topic-44-multiple-linear-regression",
            "title": "Multiple Linear Regression"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-16",
        "type": "week",
        "title": "Week 16",
        "topics": [
          {
            "id": "probability-and-statistics-topic-45-nonlinear-regression-models",
            "title": "Nonlinear Regression Models"
          },
          {
            "id": "probability-and-statistics-topic-46-linear-regression-model-using-matrices",
            "title": "Linear Regression Model Using Matrices"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-17",
        "type": "week",
        "title": "Week 17",
        "topics": [
          {
            "id": "probability-and-statistics-topic-47-properties-of-the-least-squares-estimators",
            "title": "Properties of the Least Squares Estimators"
          }
        ],
        "assessments": [],
        "milestones": []
      },
      {
        "id": "probability-and-statistics-week-18",
        "type": "week",
        "title": "Week 18",
        "topics": [],
        "assessments": [],
        "milestones": [
          "Final Semester Examination"
        ]
      }
    ],
    "topicCount": 47,
    "curriculumVersion": "66df074327cd827d80d7174bf9074e2eff69a53ffd3cd7261226cc2c6b477181"
  }
})
